/**
 * §28.2 catalog expansion, tranche 7: more fruiting-veg types (cherry/paste
 * tomato, winter squashes, melons), specialty roots and perennial vegetables,
 * and a run of culinary herbs. Same conventions as plants.ts. Reuses existing
 * families and stage templates.
 */

import type { Plant } from "../types/models";

export const plantsTranche7: Plant[] = [
  // --- Solanaceae ---
  {
    id: "cherry_tomato",
    commonName: "Cherry Tomato",
    scientificName: "Solanum lycopersicum var. cerasiforme",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 55, max: 70, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy", "rich"],
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 45, max: 90 },
    spacing: { inRowCm: 45, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["cage", "stake", "trellis"],
    commonPests: ["hornworm", "aphid", "whitefly"],
    commonDiseases: ["early blight", "blossom end rot"],
    harvest: {
      windowDays: { min: 40, max: 80 },
      yieldPerPlant: "2-4 kg",
      indicators: ["fruit fully colored and firm; indeterminate types crop until frost"],
      method: "pick ripe every few days",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Sweet, prolific, and forgiving — the gateway tomato, happy in a big container and cropping nonstop.",
    iconKey: "cherry_tomato",
    tags: ["fast", "sweet", "prolific", "container-friendly"],
  },
  {
    id: "paste_tomato",
    commonName: "Paste Tomato",
    scientificName: "Solanum lycopersicum",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    gddToMaturity: 1300,
    daysToMaturity: { min: 70, max: 85, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy", "rich"],
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 45, max: 75 },
    spacing: { inRowCm: 45, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["cage", "stake"],
    commonPests: ["hornworm", "aphid"],
    commonDiseases: ["early blight", "blossom end rot", "late blight"],
    harvest: {
      windowDays: { min: 21, max: 40 },
      yieldPerPlant: "3-5 kg",
      indicators: ["deep color and meaty walls; determinate types ripen in one flush"],
      method: "pick for sauce — determinate types set a single big crop for canning",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Dense, low-seed plum tomatoes bred for sauce and canning; many are determinate, ripening together for batch processing.",
    iconKey: "paste_tomato",
    tags: ["sauce", "determinate", "canning"],
  },
  {
    id: "cape_gooseberry",
    commonName: "Cape Gooseberry",
    scientificName: "Physalis peruviana",
    familyId: "solanaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 8, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15.5,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 110, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 60, max: 150 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    supportStructures: ["stake"],
    commonPests: ["flea beetle", "whitefly"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "1-3 kg",
      indicators: ["husk dries papery and the golden fruit drops when ripe"],
      method: "gather fallen fruit off the ground",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tart-sweet golden berries in papery lanterns — a tender perennial grown as an annual outside the tropics.",
    iconKey: "cape_gooseberry",
    tags: ["sweet", "husk-fruit", "warm-season", "tropical"],
  },

  // --- Cucurbits ---
  {
    id: "spaghetti_squash",
    commonName: "Spaghetti Squash",
    scientificName: "Cucurbita pepo",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 85, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 180, max: 240 },
    spacing: { inRowCm: 90, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "fruiting", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    commonPests: ["squash bug", "squash vine borer"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "3-5 fruits",
      indicators: ["rind hard and golden-yellow, stem drying"],
      method: "cut with a stem handle, then cure",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Winter squash whose cooked flesh pulls apart into pasta-like strands; stores well after curing.",
    iconKey: "spaghetti_squash",
    tags: ["storage", "autumn", "sprawling"],
  },
  {
    id: "acorn_squash",
    commonName: "Acorn Squash",
    scientificName: "Cucurbita pepo",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 150, max: 240 },
    spacing: { inRowCm: 90, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "fruiting", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    commonPests: ["squash bug", "squash vine borer"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "3-6 fruits",
      indicators: ["rind hard and dark green, ground spot turned orange"],
      method: "cut with a stem handle",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Single-serving ribbed winter squash with sweet flesh — quicker and more compact than the big keepers.",
    iconKey: "acorn_squash",
    tags: ["storage", "autumn", "sprawling"],
  },
  {
    id: "honeydew",
    commonName: "Honeydew Melon",
    scientificName: "Cucumis melo subsp. inodorus",
    familyId: "cucurbitaceae",
    category: "fruit",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 21,
    optSoilTempC: { min: 24, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "sandy", "warm"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 120, max: 180 },
    spacing: { inRowCm: 60, betweenRowCm: 150, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "aphid"],
    commonDiseases: ["powdery mildew", "fusarium wilt"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "2-4 fruits",
      indicators: ["rind turns creamy, blossom end softens slightly, sweet aroma"],
      method: "cut from the vine — unlike cantaloupe, it won't slip free on its own",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Smooth-skinned sweet melon that needs real heat and a long season; doesn't self-slip, so judge ripeness by smell and softness.",
    iconKey: "honeydew",
    tags: ["sweet", "summer", "heat-loving"],
  },
  {
    id: "armenian_cucumber",
    commonName: "Armenian Cucumber",
    scientificName: "Cucumis melo var. flexuosus",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 75, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 45 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 150, max: 200 },
    matureSpreadCm: { min: 90, max: 180 },
    spacing: { inRowCm: 45, betweenRowCm: 120, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "many fruits",
      indicators: ["long ribbed fruit 30-45 cm; harvest before it gets seedy"],
      method: "snip frequently; technically a melon but eaten like a burpless cucumber",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A melon that tastes and slices like a mild, never-bitter cucumber; trellis the long curling fruit to keep it straight.",
    iconKey: "armenian_cucumber",
    tags: ["heat-loving", "burpless", "climbing", "summer"],
  },

  // --- Apiaceae: bulb veg + herbs ---
  {
    id: "florence_fennel",
    commonName: "Florence Fennel",
    scientificName: "Foeniculum vulgare var. azoricum",
    familyId: "apiaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 75, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 45, max: 60 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 45, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 0, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "light feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "parsley worm"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 bulb",
      indicators: ["swollen leaf-base bulb the size of a fist; hill soil to blanch"],
      method: "cut at the base above the roots; bolts if stressed by heat",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Grown for its crisp, anise-flavored bulb rather than its fronds — steady water and cool weather keep it from bolting.",
    iconKey: "florence_fennel",
    tags: ["anise-bulb", "cool-season", "bolt-prone"],
  },
  {
    id: "cumin",
    commonName: "Cumin",
    scientificName: "Cuminum cyminum",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 10 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "sandy"],
    matureHeightCm: { min: 20, max: 40 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 10, betweenRowCm: 20, squareFootCount: 9 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew", "wilt"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "seed heads",
      indicators: ["seed umbels turn brown and dry"],
      method: "cut heads, dry, then thresh out the seed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A long, hot season is the price of homegrown cumin seed — needs heat to ripen its aromatic umbels.",
    iconKey: "cumin",
    tags: ["warm-season", "long-season", "seed-spice"],
  },
  {
    id: "caraway",
    commonName: "Caraway",
    scientificName: "Carum carvi",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["carrot rust fly", "aphid"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "leaves year one, seed year two",
      indicators: ["seed heads ripen brown in the second summer"],
      method: "cut seed heads as they brown; the root and leaves are edible too",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A cold-hardy biennial: feathery leaves the first year, then its signature aromatic seed the second.",
    iconKey: "caraway",
    tags: ["biennial", "seed-spice", "cold-hardy"],
  },

  // --- Perennial vegetables ---
  {
    id: "good_king_henry",
    commonName: "Good King Henry",
    scientificName: "Blitum bonus-henricus",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 40, max: 60 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["leaf miner", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 90, max: 180 },
      yieldPerPlant: "spring shoots and summer greens",
      indicators: ["young shoots used like asparagus; leaves like spinach"],
      method: "harvest lightly the first year; shoots and leaves thereafter",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "An old cottage-garden perennial green — slow to establish, then a dependable source of spring shoots and spinach-like leaves.",
    iconKey: "good_king_henry",
    tags: ["perennial", "spinach-substitute", "shade-tolerant", "heritage"],
  },
  {
    id: "horseradish",
    commonName: "Horseradish",
    scientificName: "Armoracia rusticana",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 140, max: 160, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["deep", "loose", "rich"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 8,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N high-K" },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["white rust"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "0.3-0.6 kg",
      indicators: ["dig the pungent roots after frost in late fall"],
      method: "lift the main root and replant a side root — it spreads aggressively",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Grown from a root cutting for fiery roots; vigorous to the point of weedy, so give it a contained, permanent corner.",
    iconKey: "horseradish",
    tags: ["perennial", "pungent", "spreads", "frost-improved"],
  },
  {
    id: "land_cress",
    commonName: "Land Cress",
    scientificName: "Barbarea verna",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["moist", "rich"],
    matureHeightCm: { min: 20, max: 30 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 8 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "light feed", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 30, max: 120 },
      yieldPerPlant: "peppery rosettes",
      indicators: ["tastes like watercress without needing running water"],
      method: "cut outer leaves; exceptionally cold-hardy through winter",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A dry-land stand-in for watercress with the same peppery bite — happy in shade and tough through hard frost.",
    iconKey: "land_cress",
    tags: ["peppery", "cold-hardy", "shade-tolerant", "watercress-substitute"],
  },
  {
    id: "elephant_garlic",
    commonName: "Elephant Garlic",
    scientificName: "Allium ampeloprasum",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 180, max: 210, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 20, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -24, max: -16 },
      plantingDepthCm: 10,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed in spring", intervalDays: 21 },
      ],
    },
    commonPests: ["onion thrips", "onion fly"],
    commonDiseases: ["white rot", "rust"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 large bulb",
      indicators: ["lower leaves brown; giant mild cloves below"],
      method: "lift and cure like garlic once tops yellow",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A leek relative that forms huge, mild garlic-like cloves — fall-planted and harvested the following summer.",
    iconKey: "elephant_garlic",
    tags: ["mild-garlic", "overwintering", "large-bulb"],
  },
  {
    id: "globe_artichoke",
    commonName: "Globe Artichoke",
    scientificName: "Cynara scolymus",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 7, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 85, max: 100, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.5, max: 7.5 },
    soilPreference: ["well-drained", "rich", "deep"],
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 90, max: 120 },
    spacing: { inRowCm: 90, betweenRowCm: 120, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
        { atStage: "budding", type: "balanced feed" },
      ],
    },
    commonPests: ["aphid", "artichoke plume moth"],
    commonDiseases: ["botrytis", "powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 60 },
      yieldPerPlant: "several buds",
      indicators: ["flower buds plump and tight, before the scales open"],
      method: "cut buds with a few cm of stem; the plant rebuds",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A statuesque perennial thistle grown for its edible flower buds; in cold zones, start early and treat as an annual.",
    iconKey: "globe_artichoke",
    tags: ["perennial", "edible-bud", "architectural", "mediterranean"],
  },
  {
    id: "cardoon",
    commonName: "Cardoon",
    scientificName: "Cynara cardunculus",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 7, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 120, max: 150, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.5, max: 7.5 },
    soilPreference: ["well-drained", "rich", "deep"],
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 90, max: 120 },
    spacing: { inRowCm: 90, betweenRowCm: 120, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "blanched stalks",
      indicators: ["blanch the stalks for 2-3 weeks before harvest to tame bitterness"],
      method: "tie and wrap the plant to blanch, then cut the inner stalks",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The artichoke's cousin grown for tender blanched leaf-stalks rather than buds — a dramatic, silvery architectural plant.",
    iconKey: "cardoon",
    tags: ["perennial", "blanched", "architectural", "mediterranean"],
  },

  // --- Lamiaceae & grass herbs ---
  {
    id: "shiso",
    commonName: "Shiso",
    scientificName: "Perilla frutescens",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 5.5, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 40, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["aphid", "flea beetle"],
    commonDiseases: ["rust"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "ongoing leaves",
      indicators: ["young leaves carry the most fragrance"],
      method: "pinch leaves; pinch flower spikes to prolong, though it self-seeds freely",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Aromatic red or green Japanese herb with a minty-anise bite — surface-sow for light, and expect it to reseed.",
    iconKey: "shiso",
    tags: ["asian", "aromatic", "self-seeding", "shade-tolerant"],
  },
  {
    id: "anise_hyssop",
    commonName: "Anise Hyssop",
    scientificName: "Agastache foeniculum",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 150 },
      yieldPerPlant: "leaves and flower spikes",
      indicators: ["anise-mint leaves and lavender flower spikes, both usable"],
      method: "snip leaves and edible flowers all season",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A drought-tough native perennial loaded with pollinators — licorice-scented leaves for tea and showy flower spikes.",
    iconKey: "anise_hyssop",
    tags: ["pollinator", "perennial", "tea", "drought-tolerant"],
  },
  {
    id: "bee_balm",
    commonName: "Bee Balm",
    scientificName: "Monarda didyma",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 2,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "leaves and flowers",
      indicators: ["minty-citrus leaves; shaggy scarlet flowers draw hummingbirds"],
      method: "snip leaves and flowers; thin stems for airflow to limit mildew",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A native mint-family perennial that's a magnet for bees and hummingbirds; give it room and air to dodge powdery mildew.",
    iconKey: "bee_balm",
    tags: ["pollinator", "hummingbird", "perennial", "tea"],
  },
  {
    id: "lemongrass",
    commonName: "Lemongrass",
    scientificName: "Cymbopogon citratus",
    familyId: "poaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 9, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 30 },
      ],
    },
    commonPests: ["rust", "aphid"],
    commonDiseases: ["rust"],
    harvest: {
      windowDays: { min: 90, max: 180 },
      yieldPerPlant: "many stalks",
      indicators: ["stalks at least 1 cm thick at the base"],
      method: "cut stalks at ground level; overwinter indoors in cold zones",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tropical clumping grass grown from a division for its citrusy stalks; thrives in a pot you can bring inside for winter.",
    iconKey: "lemongrass",
    tags: ["tropical", "aromatic", "tender-perennial", "container-friendly"],
  },
];
