/**
 * Tranche 9 — perennial fruit, berries and specialty crops that exercise the
 * new sprite archetypes (tree, cane, shrub, mat, tuber, stalk, fern,
 * succulent, cactus). Same §7 contracts as the other tranches.
 */

import type { Plant } from "../types/models";

export const plantsTranche9: Plant[] = [
  {
    id: "apple",
    commonName: "Apple",
    scientificName: "Malus domestica",
    familyId: "rosaceae",
    category: "tree",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 140, max: 180, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 250, max: 500 },
    matureSpreadCm: { min: 200, max: 450 },
    spacing: { inRowCm: 350, betweenRowCm: 400 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["stake"],
    commonPests: ["codling moth", "aphid"],
    commonDiseases: ["apple scab", "fire blight"],
    harvest: {
      windowDays: { min: 14, max: 35 },
      yieldPerPlant: "20-60 kg",
      indicators: ["full color", "seeds brown", "easy separation from spur"],
      method: "lift and twist",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Long-lived deciduous fruit tree; needs winter chill and usually a pollination partner.",
    iconKey: "apple",
    tags: ["perennial", "pollinator", "orchard"],
  },
  {
    id: "pear",
    commonName: "Pear",
    scientificName: "Pyrus communis",
    familyId: "rosaceae",
    category: "tree",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 150, max: 200, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 250, max: 450 },
    matureSpreadCm: { min: 200, max: 400 },
    spacing: { inRowCm: 350, betweenRowCm: 400 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["stake"],
    commonPests: ["codling moth", "pear psylla"],
    commonDiseases: ["fire blight", "pear scab"],
    harvest: {
      windowDays: { min: 10, max: 25 },
      yieldPerPlant: "20-50 kg",
      indicators: ["mature size", "picks when tilted horizontally"],
      method: "pick firm and ripen off-tree",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Deciduous orchard tree; best picked firm and ripened indoors.",
    iconKey: "pear",
    tags: ["perennial", "pollinator", "orchard"],
  },
  {
    id: "raspberry",
    commonName: "Raspberry",
    scientificName: "Rubus idaeus",
    familyId: "rosaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 120, max: 160, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.8, max: 6.8 },
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 60, max: 120 },
    spacing: { inRowCm: 60, betweenRowCm: 180 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["trellis"],
    commonPests: ["spotted wing drosophila", "cane borer"],
    commonDiseases: ["cane blight", "anthracnose"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "1-2 kg",
      indicators: ["berry pulls free of the core cleanly"],
      method: "pick gently when fully colored",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Cane fruit; floricanes fruit in summer. Prune spent canes yearly and trellis for airflow.",
    iconKey: "raspberry",
    tags: ["perennial", "pollinator", "cane-fruit"],
  },
  {
    id: "blackberry",
    commonName: "Blackberry",
    scientificName: "Rubus fruticosus",
    familyId: "rosaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 5, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 130, max: 170, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.5, max: 7.0 },
    matureHeightCm: { min: 120, max: 250 },
    matureSpreadCm: { min: 90, max: 180 },
    spacing: { inRowCm: 90, betweenRowCm: 200 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["trellis"],
    commonPests: ["spotted wing drosophila", "stink bug"],
    commonDiseases: ["cane blight", "orange rust"],
    harvest: {
      windowDays: { min: 21, max: 40 },
      yieldPerPlant: "2-4 kg",
      indicators: ["dull black", "berry detaches with the core"],
      method: "pick fully ripe",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Vigorous bramble; trellis the canes and remove floricanes after fruiting.",
    iconKey: "blackberry",
    tags: ["perennial", "pollinator", "cane-fruit"],
  },
  {
    id: "blueberry",
    commonName: "Blueberry",
    scientificName: "Vaccinium corymbosum",
    familyId: "ericaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 140, max: 180, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 45 },
    soilPh: { min: 4.5, max: 5.5 },
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 90, max: 150 },
    spacing: { inRowCm: 120, betweenRowCm: 180 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 21, max: 45 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "acidic ericaceous feed" }] },
    commonPests: ["spotted wing drosophila", "birds"],
    commonDiseases: ["mummy berry", "botrytis"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "2-5 kg",
      indicators: ["uniform blue", "berry rolls off with a touch"],
      method: "pick or gently roll ripe berries",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Acid-loving deciduous shrub; mulch with pine and net against birds.",
    iconKey: "blueberry",
    tags: ["perennial", "pollinator", "acid-soil"],
  },
  {
    id: "rhubarb",
    commonName: "Rhubarb",
    scientificName: "Rheum rhabarbarum",
    familyId: "polygonaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 120, max: 365, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.5, max: 7.0 },
    matureHeightCm: { min: 60, max: 100 },
    matureSpreadCm: { min: 90, max: 120 },
    spacing: { inRowCm: 90, betweenRowCm: 120 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: { schedule: [{ atStage: "vegetative", type: "compost top-dress" }] },
    commonPests: ["crown borer"],
    commonDiseases: ["crown rot"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "1-3 kg",
      indicators: ["stalks 25-40 cm and firm"],
      method: "twist stalks off at the base; discard the toxic leaf blades",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Hardy perennial grown for its tart leaf stalks; don't harvest the first year, and never eat the leaves.",
    iconKey: "rhubarb",
    tags: ["perennial", "cool-season"],
  },
  {
    id: "asparagus",
    commonName: "Asparagus",
    scientificName: "Asparagus officinalis",
    familyId: "asparagaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    daysToMaturity: { min: 120, max: 730, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.5, max: 7.5 },
    matureHeightCm: { min: 100, max: 150 },
    matureSpreadCm: { min: 40, max: 60 },
    spacing: { inRowCm: 40, betweenRowCm: 120 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -6, max: 0 },
      plantingDepthCm: 15,
      germinationDays: { min: 14, max: 35 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    commonPests: ["asparagus beetle"],
    commonDiseases: ["rust", "crown rot"],
    harvest: {
      windowDays: { min: 21, max: 56 },
      yieldPerPlant: "0.2-0.5 kg",
      indicators: ["spears 18-22 cm with tight tips"],
      method: "snap or cut spears at ground level; stop when spears thin",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Long-lived perennial from crowns; let it fern out to build the bed before harvesting (year 3+).",
    iconKey: "asparagus",
    tags: ["perennial", "spring"],
  },
  {
    id: "aloe_vera",
    commonName: "Aloe Vera",
    scientificName: "Aloe barbadensis",
    familyId: "asphodelaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 9, max: 12 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 15,
    daysToMaturity: { min: 120, max: 240, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 5, max: 15 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 40, betweenRowCm: 50 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 1, max: 6 },
      plantingDepthCm: 3,
      germinationDays: { min: 21, max: 35 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: { schedule: [{ atStage: "vegetative", type: "dilute cactus feed" }] },
    commonPests: ["mealybug", "scale"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 30, max: 120 },
      yieldPerPlant: "as needed",
      indicators: ["outer leaves thick and plump"],
      method: "cut mature outer leaves at the base",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Tender succulent grown in gritty soil; water sparingly and protect from frost.",
    iconKey: "aloe_vera",
    tags: ["perennial", "container-friendly", "drought-tolerant"],
  },
  {
    id: "prickly_pear",
    commonName: "Prickly Pear",
    scientificName: "Opuntia ficus-indica",
    familyId: "cactaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 8, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    daysToMaturity: { min: 150, max: 300, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 5, max: 15 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 60, max: 200 },
    matureSpreadCm: { min: 60, max: 180 },
    spacing: { inRowCm: 120, betweenRowCm: 150 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 1, max: 6 },
      plantingDepthCm: 5,
      germinationDays: { min: 21, max: 45 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "dilute cactus feed" }] },
    commonPests: ["cochineal scale"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "2-8 kg",
      indicators: ["tunas fully colored", "glochids loosen"],
      method: "twist off fruit with tongs; brush off glochids",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Drought-hardy cactus grown from pads; edible pads (nopales) and fruit (tunas). Mind the glochids.",
    iconKey: "prickly_pear",
    tags: ["perennial", "drought-tolerant", "pollinator"],
  },
];
