/**
 * §28.2 catalog expansion, tranche 5: more vegetable staples — warm-season
 * grain/pod/tuber crops (corn, okra, sweet potato, cowpea, chickpea), brassica
 * roots and Asian greens, chicories, and dual-purpose amaranth. Same
 * conventions as plants.ts. Introduces the poaceae, malvaceae, and
 * convolvulaceae families; reuses existing stage templates.
 */

import type { Plant } from "../types/models";

export const plantsTranche5: Plant[] = [
  // --- Warm-season grain / pod / tuber ---
  {
    id: "sweet_corn",
    commonName: "Sweet Corn",
    scientificName: "Zea mays",
    familyId: "poaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 16,
    optSoilTempC: { min: 21, max: 30 },
    gddBaseTempC: 10,
    gddToMaturity: 1400,
    daysToMaturity: { min: 60, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 150, max: 250 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
        { atStage: "flowering", type: "balanced feed at tasseling" },
      ],
    },
    commonPests: ["corn earworm", "European corn borer", "raccoon"],
    commonDiseases: ["corn smut", "common rust"],
    harvest: {
      windowDays: { min: 7, max: 14 },
      yieldPerPlant: "1-2 ears",
      indicators: ["silks brown and dry; kernels spurt milky juice when pierced"],
      method: "snap ears downward; sugars fade fast, so eat soon",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Wind-pollinated, so plant in blocks of at least 4 short rows, not one long one; a hungry crop that wants rich soil.",
    iconKey: "sweet_corn",
    tags: ["block-planting", "heavy-feeder", "summer"],
  },
  {
    id: "okra",
    commonName: "Okra",
    scientificName: "Abelmoschus esculentus",
    familyId: "malvaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 18,
    optSoilTempC: { min: 24, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 50, max: 65, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "balanced feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "corn earworm", "stink bug"],
    commonDiseases: ["fusarium wilt", "root-knot nematode"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "many pods",
      indicators: ["pods 7-10 cm and snapping easily; tough if left longer"],
      method: "cut every 1-2 days, gloved — the pods and stems can irritate skin",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Loves real heat and keeps cranking out pods if you pick daily; a Southern-garden mainstay.",
    iconKey: "okra",
    tags: ["heat-loving", "prolific", "southern"],
  },
  {
    id: "sweet_potato",
    commonName: "Sweet Potato",
    scientificName: "Ipomoea batatas",
    familyId: "convolvulaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 8, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.5, max: 6.5 },
    soilPreference: ["well-drained", "sandy", "loose"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 90, max: 180 },
    spacing: { inRowCm: 30, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 8,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "low-N — excess nitrogen grows vines, not roots" },
        { atStage: "fruiting", type: "low-N high-K for tuber fill" },
      ],
    },
    commonPests: ["sweet potato weevil", "flea beetle"],
    commonDiseases: ["stem rot", "scurf"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1-3 kg",
      indicators: ["dig before first frost once skins have set"],
      method: "lift carefully with a fork, then cure warm and humid for sweetness",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Grown from rooted slips in warm soil; a sprawling, heat-loving vine that stores for months once cured.",
    iconKey: "sweet_potato",
    tags: ["heat-loving", "storage", "vining"],
  },
  {
    id: "cowpea",
    commonName: "Cowpea",
    scientificName: "Vigna unguiculata",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 5.5, max: 7.0 },
    soilPreference: ["well-drained", "sandy"],
    matureHeightCm: { min: 30, max: 90 },
    matureSpreadCm: { min: 20, max: 45 },
    spacing: { inRowCm: 10, betweenRowCm: 60, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    commonPests: ["cowpea curculio", "aphid"],
    commonDiseases: ["rust", "powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 50 },
      yieldPerPlant: "0.3-0.6 kg",
      indicators: ["snap young, shell when plump, or dry on the vine"],
      method: "pick at the stage you want; thrives in heat and drought",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Black-eyed peas and their kin — tough, drought-proof legumes that improve poor soil while they crop.",
    iconKey: "cowpea",
    tags: ["heat-loving", "drought-tolerant", "southern", "protein"],
  },
  {
    id: "chickpea",
    commonName: "Chickpea",
    scientificName: "Cicer arietinum",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "sandy"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 10, betweenRowCm: 45, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    commonPests: ["aphid", "leaf miner"],
    commonDiseases: ["ascochyta blight", "fusarium wilt"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.2-0.4 kg",
      indicators: ["pods dry and rattly for storage chickpeas, or green for fresh"],
      method: "pull the whole plant once most pods brown",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A cool-tolerant dry bean that resents wet feet — needs a long, fairly dry season to fill its pods.",
    iconKey: "chickpea",
    tags: ["drought-tolerant", "protein", "dry-bean"],
  },

  // --- Brassica roots & Asian greens ---
  {
    id: "kohlrabi",
    commonName: "Kohlrabi",
    scientificName: "Brassica oleracea var. gongylodes",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 45, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 20, max: 25 },
    spacing: { inRowCm: 20, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -5, max: -3 },
      directSowWeeksFromLastFrost: { min: -2, max: 3 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_root_fast",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "balanced feed as the bulb swells" },
      ],
    },
    commonPests: ["cabbage worm", "flea beetle", "aphid"],
    commonDiseases: ["clubroot", "black rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 bulb",
      indicators: ["swollen stem 5-8 cm; turns woody if left too long"],
      method: "cut at the base while still tender",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "The above-ground 'root' — a fast, crisp swollen stem that's sweetest harvested young.",
    iconKey: "kohlrabi",
    tags: ["fast", "cool-season", "unusual"],
  },
  {
    id: "rutabaga",
    commonName: "Rutabaga",
    scientificName: "Brassica napus",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "loose"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 35, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 2, max: 8 },
      plantingDepthCm: 1.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N high-K for roots" },
      ],
    },
    commonPests: ["root maggot", "flea beetle"],
    commonDiseases: ["clubroot", "powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "0.3-0.8 kg",
      indicators: ["roots 8-12 cm; sweeter after a frost"],
      method: "pull as needed — stores for months in a cold cellar",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A sweet, dense storage root best sown for fall; cold weather turns its starch to sugar.",
    iconKey: "rutabaga",
    tags: ["storage", "frost-sweetened", "cool-season"],
  },
  {
    id: "daikon",
    commonName: "Daikon Radish",
    scientificName: "Raphanus sativus var. longipinnatus",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "deep", "loose"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 10, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 2, max: 8 },
      plantingDepthCm: 1.5,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_root_fast",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N high-K for roots" },
      ],
    },
    commonPests: ["flea beetle", "root maggot"],
    commonDiseases: ["clubroot", "downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.3-0.7 kg per root",
      indicators: ["long white roots up to 30 cm; mild before they get pithy"],
      method: "loosen the soil and pull — doubles as a soil-busting cover crop",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Big, mild Asian radish best as a fall crop; its deep taproot breaks up compacted ground.",
    iconKey: "daikon",
    tags: ["fall", "storage", "large-root"],
  },
  {
    id: "napa_cabbage",
    commonName: "Napa Cabbage",
    scientificName: "Brassica rapa subsp. pekinensis",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 80, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "moist"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 25, max: 35 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 4, max: 10 },
      transplantWeeksFromLastFrost: { min: 4, max: 8 },
      plantingDepthCm: 1,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 14 },
      ],
    },
    commonPests: ["cabbage worm", "flea beetle", "slug"],
    commonDiseases: ["clubroot", "soft rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 head, 1-2 kg",
      indicators: ["head firm and dense to a squeeze"],
      method: "cut at the base; best grown as a fall crop to avoid bolting",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The crisp barrel-shaped cabbage for kimchi and stir-fry — bolts in spring heat, so time it for fall.",
    iconKey: "napa_cabbage",
    tags: ["fall", "asian-greens", "heading"],
  },
  {
    id: "mizuna",
    commonName: "Mizuna",
    scientificName: "Brassica rapa var. nipposinica",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 35, max: 45, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 20, max: 40 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 8 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 21, max: 60 },
      yieldPerPlant: "repeated cuttings",
      indicators: ["feathery leaves 10-15 cm; mild mustard tang"],
      method: "cut outer leaves — it regrows for several harvests",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Fast, frilly, mild-mustard salad green that tolerates cold and a bit of shade.",
    iconKey: "mizuna",
    tags: ["fast", "mild-mustard", "cut-and-come-again", "shade-tolerant"],
  },
  {
    id: "tatsoi",
    commonName: "Tatsoi",
    scientificName: "Brassica rapa var. narinosa",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 40, max: 50, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 15, max: 25 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 8 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 21, max: 50 },
      yieldPerPlant: "rosettes",
      indicators: ["glossy spoon-shaped leaves in a flat rosette"],
      method: "cut the whole rosette or pick outer leaves",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Exceptionally cold-hardy spoon-leaf green — keeps cropping into hard frost under a row cover.",
    iconKey: "tatsoi",
    tags: ["cold-hardy", "asian-greens", "fast", "shade-tolerant"],
  },

  // --- Apiaceae root ---
  {
    id: "celeriac",
    commonName: "Celeriac",
    scientificName: "Apium graveolens var. rapaceum",
    familyId: "apiaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 2, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 100, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 30, max: 50 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 25, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 40, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["carrot rust fly", "celery leaf miner"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "1 knobby root, 0.5-1 kg",
      indicators: ["swollen base 8-12 cm across"],
      method: "lift, then trim the roots and tops",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "hard",
    description:
      "Knobby celery-flavored root that needs a long, steadily moist season — never let it dry out.",
    iconKey: "celeriac",
    tags: ["long-season", "thirsty", "storage"],
  },

  // --- Chicories ---
  {
    id: "endive",
    commonName: "Endive",
    scientificName: "Cichorium endivia",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 25, max: 40 },
    matureSpreadCm: { min: 30, max: 40 },
    spacing: { inRowCm: 30, betweenRowCm: 40, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -5, max: -3 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "slug"],
    commonDiseases: ["downy mildew", "bottom rot"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 head",
      indicators: ["full frilly rosette; blanch the center to soften the bitterness"],
      method: "cut at the base",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Frilly, slightly bitter salad green for cool weather; tying up the outer leaves blanches a sweeter heart.",
    iconKey: "endive",
    tags: ["bitter-green", "cool-season", "blanched"],
  },
  {
    id: "radicchio",
    commonName: "Radicchio",
    scientificName: "Cichorium intybus",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 70, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 20, max: 30 },
    matureSpreadCm: { min: 25, max: 35 },
    spacing: { inRowCm: 25, betweenRowCm: 35, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 2, max: 8 },
      transplantWeeksFromLastFrost: { min: 2, max: 6 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "slug"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 head",
      indicators: ["firm red-and-white head after cool weather colors it up"],
      method: "cut at the base; cold sweetens the bitterness and deepens the color",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Heading chicory that turns ruby in the cold — best timed so the head forms during chilly fall weather.",
    iconKey: "radicchio",
    tags: ["chicory", "fall", "frost-colored", "bitter-green"],
  },
  {
    id: "sunchoke",
    commonName: "Jerusalem Artichoke",
    scientificName: "Helianthus tuberosus",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 120, max: 150, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 5.8, max: 7.5 },
    soilPreference: ["well-drained", "tolerates poor soil"],
    matureHeightCm: { min: 180, max: 300 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 45, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 10,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — it crops in poor soil" }],
    },
    supportStructures: ["stake"],
    commonPests: ["aphid"],
    commonDiseases: ["sclerotinia"],
    harvest: {
      windowDays: { min: 30, max: 120 },
      yieldPerPlant: "1-2 kg of tubers",
      indicators: ["dig after frost blackens the tops; sweetest in cold ground"],
      method: "dig as needed — leave a few and it returns (often aggressively)",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A towering sunflower relative grown for knobbly tubers; vigorous to the point of invasive, so corral it.",
    iconKey: "sunchoke",
    tags: ["perennial", "vigorous", "tubers", "spreads"],
  },

  // --- Solanaceae, cucurbit, amaranth ---
  {
    id: "ground_cherry",
    commonName: "Ground Cherry",
    scientificName: "Physalis pruinosa",
    familyId: "solanaceae",
    category: "fruit",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15.5,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 7, max: 21 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "three-lined potato beetle"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "1-2 kg",
      indicators: ["husks turn papery tan and the fruit drops — that's ripe"],
      method: "gather the fallen husked fruit off the ground",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Low sprawling cousin of the tomatillo with sweet, pineapple-ish fruit in papery husks; self-seeds readily.",
    iconKey: "ground_cherry",
    tags: ["sweet", "husk-fruit", "self-seeding", "warm-season"],
  },
  {
    id: "gourd",
    commonName: "Hardshell Gourd",
    scientificName: "Lagenaria siceraria",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 130, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 240, max: 360 },
    spacing: { inRowCm: 90, betweenRowCm: 240, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 21 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["squash bug", "cucumber beetle"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "several gourds",
      indicators: ["rind hard and the stem dry; trellising keeps shapes clean"],
      method: "cut with a stem, then cure for weeks until light and hollow",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Long-season vining gourd grown for dippers, birdhouses, and crafts; needs a long warm season to harden off.",
    iconKey: "gourd",
    tags: ["ornamental", "hardshell", "crafts", "sprawling"],
  },
  {
    id: "amaranth",
    commonName: "Amaranth",
    scientificName: "Amaranthus tricolor",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 30, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 60, max: 180 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N for leaf crops", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "flea beetle"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "greens, then grain",
      indicators: ["young leaves for greens; bronzed seed heads for grain"],
      method: "cut leaves young; rub out the dry seed heads at season's end",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Heat-proof and drought-tough — a dual-purpose plant grown for tender greens and protein-rich grain alike.",
    iconKey: "amaranth",
    tags: ["heat-loving", "dual-purpose", "grain", "greens"],
  },
];
