/**
 * Tranche 10 — more perennial fruit (stone fruit, figs, currants, grapes),
 * further populating the tree / shrub / climbing archetypes. (Existing thyme
 * is restyled to the mat archetype in the sprite layer.) Same §7 contracts.
 */

import type { Plant } from "../types/models";

export const plantsTranche10: Plant[] = [
  {
    id: "cherry",
    commonName: "Cherry",
    scientificName: "Prunus avium",
    familyId: "rosaceae",
    category: "tree",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    daysToMaturity: { min: 120, max: 160, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 250, max: 500 },
    matureSpreadCm: { min: 200, max: 450 },
    spacing: { inRowCm: 400, betweenRowCm: 450 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["stake"],
    commonPests: ["cherry fruit fly", "birds"],
    commonDiseases: ["brown rot", "bacterial canker"],
    harvest: {
      windowDays: { min: 10, max: 21 },
      yieldPerPlant: "10-40 kg",
      indicators: ["full deep color", "sweet and firm"],
      method: "pick with stems to store longer",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Deciduous stone-fruit tree; net against birds and prune in dry weather to avoid canker.",
    iconKey: "cherry",
    tags: ["perennial", "pollinator", "orchard"],
  },
  {
    id: "fig",
    commonName: "Fig",
    scientificName: "Ficus carica",
    familyId: "moraceae",
    category: "tree",
    lifecycle: "perennial",
    hardinessZones: { min: 7, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 12,
    daysToMaturity: { min: 120, max: 180, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    matureHeightCm: { min: 200, max: 500 },
    matureSpreadCm: { min: 200, max: 500 },
    spacing: { inRowCm: 400, betweenRowCm: 450 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 1, max: 6 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    commonPests: ["fig beetle", "birds"],
    commonDiseases: ["fig rust", "root knot nematode"],
    harvest: {
      windowDays: { min: 21, max: 60 },
      yieldPerPlant: "10-30 kg",
      indicators: ["fruit softens and droops on its stalk"],
      method: "pick when fully soft; they don't ripen off the tree",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Warm-climate deciduous tree; wrap or move containers in cold zones. Fruit must ripen fully on the tree.",
    iconKey: "fig",
    tags: ["perennial", "container-friendly", "heat-loving"],
  },
  {
    id: "currant",
    commonName: "Currant",
    scientificName: "Ribes rubrum",
    familyId: "grossulariaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 6,
    daysToMaturity: { min: 100, max: 140, from: "transplant" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 90, max: 150 },
    spacing: { inRowCm: 120, betweenRowCm: 150 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    commonPests: ["currant aphid", "sawfly"],
    commonDiseases: ["powdery mildew", "white pine blister rust"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "3-5 kg",
      indicators: ["whole strigs fully colored"],
      method: "snip entire clusters (strigs)",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Hardy berry shrub that tolerates part shade; fruits on two- and three-year-old wood.",
    iconKey: "currant",
    tags: ["perennial", "shade-tolerant", "cool-season"],
  },
  {
    id: "gooseberry",
    commonName: "Gooseberry",
    scientificName: "Ribes uva-crispa",
    familyId: "grossulariaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 8 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 6,
    daysToMaturity: { min: 100, max: 140, from: "transplant" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 90, max: 150 },
    spacing: { inRowCm: 120, betweenRowCm: 150 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -4, max: 2 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 30 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    commonPests: ["gooseberry sawfly", "currant borer"],
    commonDiseases: ["powdery mildew", "leaf spot"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "3-5 kg",
      indicators: ["berries soften and color up"],
      method: "pick wearing gloves; many cultivars are thorny",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description: "Thorny, hardy berry shrub for cool climates; tolerates part shade and prefers airflow.",
    iconKey: "gooseberry",
    tags: ["perennial", "shade-tolerant", "cool-season"],
  },
  {
    id: "grape",
    commonName: "Grape",
    scientificName: "Vitis vinifera",
    familyId: "vitaceae",
    category: "fruit",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 10 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 10,
    daysToMaturity: { min: 140, max: 200, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 30 },
    soilPh: { min: 5.5, max: 7.0 },
    matureHeightCm: { min: 150, max: 300 },
    matureSpreadCm: { min: 150, max: 400 },
    spacing: { inRowCm: 180, betweenRowCm: 250 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 5,
      germinationDays: { min: 14, max: 35 },
    },
    stageTemplateId: "tmpl_perennial_fruit",
    fertilization: { schedule: [{ atStage: "vegetative", type: "balanced 10-10-10" }] },
    supportStructures: ["trellis"],
    commonPests: ["grape berry moth", "japanese beetle", "birds"],
    commonDiseases: ["downy mildew", "black rot", "powdery mildew"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "5-15 kg",
      indicators: ["full color", "sweet to taste", "seeds brown"],
      method: "cut whole bunches at the stem",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description: "Long-lived woody vine; needs a sturdy trellis and hard annual pruning for good fruit.",
    iconKey: "grape",
    tags: ["perennial", "vine", "trellis"],
  },
];
