/**
 * §28.2 catalog expansion, tranche 4: culinary herbs and cottage-garden
 * flowers — the Mediterranean perennials (oregano, sage, rosemary, lavender),
 * a few tender/annual herbs, and easy pollinator flowers. Same conventions as
 * plants.ts. Reuses existing families plus the herb and flower templates.
 */

import type { Plant } from "../types/models";

export const plantsTranche4: Plant[] = [
  // --- Lamiaceae: Mediterranean perennial herbs ---
  {
    id: "oregano",
    commonName: "Oregano",
    scientificName: "Origanum vulgare",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 10 },
    heatTolerance: "high",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "lean", "gritty"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — rich soil dilutes flavor" }],
    },
    commonPests: ["aphid", "spider mite"],
    commonDiseases: ["root rot", "powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 180 },
      yieldPerPlant: "frequent handfuls",
      indicators: ["most pungent just before flowers open"],
      method: "snip sprigs above a leaf pair",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tough Mediterranean perennial — lean soil and dry feet give the strongest flavor; a pollinator favorite in bloom.",
    iconKey: "oregano",
    tags: ["mediterranean", "perennial", "pollinator", "drought-tolerant"],
  },
  {
    id: "sage",
    commonName: "Sage",
    scientificName: "Salvia officinalis",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 75, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 30, max: 75 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["spittlebug", "spider mite"],
    commonDiseases: ["powdery mildew", "root rot"],
    harvest: {
      windowDays: { min: 120, max: 200 },
      yieldPerPlant: "frequent handfuls",
      indicators: ["leaves richest before flowering; pick all season"],
      method: "snip sprigs; renew woody plants every few years",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Silvery, woody, and drought-proof — one plant supplies a kitchen and feeds bees when it blooms.",
    iconKey: "sage",
    tags: ["mediterranean", "perennial", "drought-tolerant", "culinary"],
  },
  {
    id: "rosemary",
    commonName: "Rosemary",
    scientificName: "Salvia rosmarinus",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 7, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 130, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "gritty", "lean"],
    matureHeightCm: { min: 60, max: 150 },
    matureSpreadCm: { min: 60, max: 120 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — it thrives on neglect" }],
    },
    commonPests: ["spittlebug", "aphid"],
    commonDiseases: ["root rot", "powdery mildew"],
    harvest: {
      windowDays: { min: 200, max: 300 },
      yieldPerPlant: "year-round sprigs",
      indicators: ["harvest any time; new growth is most tender"],
      method: "snip woody stems; in cold zones overwinter in a pot",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Evergreen and slow from seed (most gardeners start from a plant); needs sharp drainage and winter protection below zone 7.",
    iconKey: "rosemary",
    tags: ["mediterranean", "evergreen", "drought-tolerant", "tender-perennial"],
  },
  {
    id: "lavender",
    commonName: "Lavender",
    scientificName: "Lavandula angustifolia",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 5, max: 9 },
    heatTolerance: "high",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 200, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 10, max: 20 },
    soilPh: { min: 6.5, max: 8.0 },
    soilPreference: ["well-drained", "gritty", "alkaline"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 45, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — lean, gritty soil preferred" }],
    },
    commonPests: ["spittlebug", "whitefly"],
    commonDiseases: ["root rot", "phytophthora"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "many flower spikes",
      indicators: ["cut when the lowest florets on a spike just open"],
      method: "cut spikes for drying; shear after bloom to keep it tidy",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Fragrant, bee-laden, and slow from seed — the make-or-break factor is drainage; it rots in wet ground.",
    iconKey: "lavender",
    tags: ["mediterranean", "pollinator", "fragrant", "drought-tolerant"],
  },
  {
    id: "marjoram",
    commonName: "Sweet Marjoram",
    scientificName: "Origanum majorana",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 7, max: 9 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 8, max: 14 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["aphid", "spider mite"],
    commonDiseases: ["damping off"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "frequent handfuls",
      indicators: ["sweetest just before the knot-like buds open"],
      method: "snip sprigs; grown as an annual where winters are cold",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Milder, sweeter cousin of oregano — tender, so most gardeners grow it fresh each year.",
    iconKey: "marjoram",
    tags: ["mediterranean", "sweet", "tender", "culinary"],
  },
  {
    id: "savory",
    commonName: "Summer Savory",
    scientificName: "Satureja hortensis",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "light"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 10, max: 15 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 45, max: 90 },
      yieldPerPlant: "frequent sprigs",
      indicators: ["best flavor just before flowering"],
      method: "snip sprigs; the classic partner for green beans",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Peppery annual herb that's quick from seed — a traditional companion to beans, in the pot and the bed.",
    iconKey: "savory",
    tags: ["peppery", "annual", "culinary"],
  },
  {
    id: "catnip",
    commonName: "Catnip",
    scientificName: "Nepeta cataria",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 70, max: 85, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 50, max: 100 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 180 },
      yieldPerPlant: "frequent cuttings",
      indicators: ["most potent at first flowering"],
      method: "cut stems; dry for cats or steep for tea",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Vigorous, drought-tough perennial that draws pollinators (and cats); cut it back to curb self-seeding.",
    iconKey: "catnip",
    tags: ["pollinator", "perennial", "drought-tolerant"],
  },

  // --- Amaryllidaceae herb ---
  {
    id: "chives",
    commonName: "Chives",
    scientificName: "Allium schoenoprasum",
    familyId: "amaryllidaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 20, max: 40 },
    matureSpreadCm: { min: 15, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 20, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed after cutting", intervalDays: 30 },
      ],
    },
    commonPests: ["onion thrips", "aphid"],
    commonDiseases: ["downy mildew", "rust"],
    harvest: {
      windowDays: { min: 120, max: 200 },
      yieldPerPlant: "frequent cuttings",
      indicators: ["leaves 15 cm+; edible pom-pom flowers too"],
      method: "snip 2 cm above the soil; it regrows quickly",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "The easiest perennial allium — a tidy clump of oniony spears, with pink pollinator flowers in spring.",
    iconKey: "chives",
    tags: ["perennial", "pollinator", "cut-and-regrow"],
  },

  // --- Asteraceae: herb + flowers ---
  {
    id: "tarragon",
    commonName: "Tarragon",
    scientificName: "Artemisia dracunculus",
    familyId: "asteraceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 8 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 2,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot", "powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 150 },
      yieldPerPlant: "frequent sprigs",
      indicators: ["young leaves carry the most anise aroma"],
      method: "snip sprigs; for true French tarragon, plant divisions",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Anise-scented kitchen perennial — wants sharp drainage and benefits from dividing every few years.",
    iconKey: "tarragon",
    tags: ["anise", "perennial", "culinary", "drought-tolerant"],
  },
  {
    id: "chamomile",
    commonName: "Chamomile",
    scientificName: "Matricaria chamomilla",
    familyId: "asteraceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 65, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 5.6, max: 7.5 },
    soilPreference: ["well-drained", "light"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 15, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 20, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — lean soil is fine" }],
    },
    commonPests: ["aphid", "thrips"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "many flower heads",
      indicators: ["petals fully open and beginning to reflex"],
      method: "pluck flower heads every few days; dries well for tea",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Daisy-like tea flower that self-seeds happily — surface-sow, since the tiny seeds need light to germinate.",
    iconKey: "chamomile",
    tags: ["tea", "pollinator", "self-seeding", "flower"],
  },
  {
    id: "cosmos",
    commonName: "Cosmos",
    scientificName: "Cosmos bipinnatus",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 60, max: 150 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — lean soil means more blooms" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew", "aster yellows"],
    harvest: {
      windowDays: { min: 60, max: 90 },
      yieldPerPlant: "many cutting stems",
      indicators: ["cut as buds just crack open"],
      method: "cut for the vase and deadhead to extend bloom",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Airy, fast, and forgiving — thrives on neglect and lean soil, blooming until frost as a pollinator beacon.",
    iconKey: "cosmos",
    tags: ["pollinator", "cut-flower", "drought-tolerant", "self-seeding"],
  },
  {
    id: "calendula",
    commonName: "Calendula",
    scientificName: "Calendula officinalis",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 20, max: 40 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "budding", type: "light feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "whitefly"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "many flower heads",
      indicators: ["petals fully open; pick often to keep it blooming"],
      method: "pluck heads and deadhead; petals are edible",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Cheerful cool-season pot marigold with edible petals — blooms early, reseeds, and shrugs off light frost.",
    iconKey: "calendula",
    tags: ["edible-flower", "pollinator", "cool-season", "cut-flower"],
  },

  // --- Apiaceae herbs ---
  {
    id: "fennel",
    commonName: "Fennel",
    scientificName: "Foeniculum vulgare",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["parsley worm", "aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 150 },
      yieldPerPlant: "fronds, pollen, and seed",
      indicators: ["snip fronds any time; let heads dry for seed"],
      method: "cut fronds; collect seed as umbels brown",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tall anise-scented herb and a swallowtail host — plant it apart from beans and dill, as it inhibits nearby growth.",
    iconKey: "fennel",
    tags: ["anise", "pollinator", "perennial", "self-seeding"],
  },
  {
    id: "chervil",
    commonName: "Chervil",
    scientificName: "Anthriscus cerefolium",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 40, max: 60, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["moist", "rich"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 15, betweenRowCm: 20, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["damping off"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "frequent ferny leaves",
      indicators: ["pick young leaves before it bolts in heat"],
      method: "snip outer leaves; succession-sow for a steady supply",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Delicate anise-parsley for cool, shaded corners — fast, prone to bolting, and happiest out of harsh sun.",
    iconKey: "chervil",
    tags: ["delicate", "shade-tolerant", "cool-season", "fast"],
  },
  {
    id: "lovage",
    commonName: "Lovage",
    scientificName: "Levisticum officinale",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid", "leaf miner"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 120, max: 200 },
      yieldPerPlant: "abundant celery-flavored leaves",
      indicators: ["young leaves and stalks are most tender"],
      method: "snip outer stalks; one plant supplies a household",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Big, hardy perennial that tastes of intense celery — long-lived and best given a back-of-bed corner to itself.",
    iconKey: "lovage",
    tags: ["celery-flavor", "perennial", "large", "culinary"],
  },
];
