/**
 * §28.2 catalog expansion, tranche 3: common warm- and cool-season staples
 * that round out the core encyclopedia — fruiting solanums/cucurbits, more
 * legumes, brassicas, roots, alliums, and a cut-flower. Same conventions as
 * plants.ts: week offsets relative to last spring frost (negative = before),
 * temperatures °C, lengths cm, water mm/week. Reuses the existing families
 * and stage templates so no new scaffolding is required.
 */

import type { Plant } from "../types/models";

export const plantsTranche3: Plant[] = [
  // --- Solanaceae ---
  {
    id: "eggplant",
    commonName: "Eggplant",
    scientificName: "Solanum melongena",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 12 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 65, max: 85, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.5, max: 6.8 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 45, max: 75 },
    spacing: { inRowCm: 45, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["stake", "cage"],
    commonPests: ["flea beetle", "aphid", "hornworm"],
    commonDiseases: ["verticillium wilt", "blossom end rot"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "6-10 fruits",
      indicators: ["skin glossy and firm, before seeds darken"],
      method: "snip with a short stem",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Heat-loving solanum; needs a long warm season and steady feeding to size up.",
    iconKey: "eggplant",
    tags: ["warm-season", "container-friendly", "summer"],
  },
  {
    id: "hot_pepper",
    commonName: "Hot Pepper",
    scientificName: "Capsicum annuum",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 12 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 90, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 5.5, max: 6.8 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 38, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 21 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["stake"],
    commonPests: ["aphid", "flea beetle", "pepper weevil"],
    commonDiseases: ["bacterial leaf spot", "blossom end rot"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "20-40 fruits",
      indicators: ["full mature color, firm; heat rises as they ripen"],
      method: "snip — stems are brittle",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Compact, productive, and slow to start — warmth and patience reward you with a long harvest.",
    iconKey: "hot_pepper",
    tags: ["spicy", "container-friendly", "warm-season"],
  },
  {
    id: "tomatillo",
    commonName: "Tomatillo",
    scientificName: "Physalis philadelphica",
    familyId: "solanaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 12 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15.5,
    optSoilTempC: { min: 21, max: 29 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 75, max: 100, from: "transplant" },
    photoperiod: "day_neutral",
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.5, max: 7.0 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 90, max: 120 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "flowering", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["cage"],
    commonPests: ["three-lined potato beetle", "aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "2-4 kg",
      indicators: ["husk fills out and splits; fruit firm"],
      method: "pick when husk splits",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Sprawling salsa-verde staple — plant at least two for good pollination and fruit set.",
    iconKey: "tomatillo",
    tags: ["warm-season", "salsa", "needs-a-pair"],
  },

  // --- Cucurbitaceae ---
  {
    id: "summer_squash",
    commonName: "Summer Squash",
    scientificName: "Cucurbita pepo",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 45, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 50 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 90, max: 120 },
    spacing: { inRowCm: 60, betweenRowCm: 120, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    commonPests: ["squash bug", "squash vine borer", "cucumber beetle"],
    commonDiseases: ["powdery mildew", "bacterial wilt"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "10-25 fruits",
      indicators: ["15-20 cm, skin still tender to a thumbnail"],
      method: "snip frequently — overgrown fruit slows the plant",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Bushy and absurdly prolific; pick young and often to keep it producing.",
    iconKey: "summer_squash",
    tags: ["fast", "prolific", "summer"],
  },
  {
    id: "winter_squash",
    commonName: "Winter Squash",
    scientificName: "Cucurbita moschata",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 85, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 180, max: 300 },
    spacing: { inRowCm: 90, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "fruiting", type: "low-N high-K", intervalDays: 21 },
      ],
    },
    commonPests: ["squash bug", "squash vine borer"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "3-6 fruits",
      indicators: ["rind hard, dull-colored; stem corking"],
      method: "cut leaving a 5 cm stem handle, then cure",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Long-season sprawler that stores for months once cured — give it room to roam.",
    iconKey: "winter_squash",
    tags: ["storage", "sprawling", "autumn"],
  },
  {
    id: "pumpkin",
    commonName: "Pumpkin",
    scientificName: "Cucurbita pepo",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    optSoilTempC: { min: 21, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 45 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 180, max: 300 },
    spacing: { inRowCm: 120, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "high-N for vine growth", intervalDays: 21 },
        { atStage: "fruiting", type: "low-N high-K" },
      ],
    },
    commonPests: ["squash bug", "squash vine borer", "cucumber beetle"],
    commonDiseases: ["powdery mildew", "downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1-4 fruits",
      indicators: ["deep uniform color, hard rind, dry stem"],
      method: "cut leaving a handle; cure in the sun",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The classic autumn sprawler — thin to the best fruit for show-size pumpkins.",
    iconKey: "pumpkin",
    tags: ["autumn", "sprawling", "storage"],
  },
  {
    id: "watermelon",
    commonName: "Watermelon",
    scientificName: "Citrullus lanatus",
    familyId: "cucurbitaceae",
    category: "fruit",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 4,
    minSoilTempC: 21,
    optSoilTempC: { min: 24, max: 35 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "sandy", "warm"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 180, max: 300 },
    spacing: { inRowCm: 90, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "balanced feed", intervalDays: 14 },
        { atStage: "flowering", type: "low-N high-K" },
      ],
    },
    commonPests: ["cucumber beetle", "aphid"],
    commonDiseases: ["fusarium wilt", "anthracnose"],
    harvest: {
      windowDays: { min: 14, max: 21 },
      yieldPerPlant: "2-4 fruits",
      indicators: ["curl by the stem dries brown, ground spot turns yellow, dull thump"],
      method: "cut from the vine — they don't sweeten off the plant",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Wants real heat and a long season; consistent water until fruit sizes, then ease off to concentrate sugar.",
    iconKey: "watermelon",
    tags: ["heat-loving", "summer", "sprawling"],
  },
  {
    id: "cantaloupe",
    commonName: "Cantaloupe",
    scientificName: "Cucumis melo",
    familyId: "cucurbitaceae",
    category: "fruit",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 5,
    minSoilTempC: 21,
    optSoilTempC: { min: 24, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "sandy", "warm"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 120, max: 180 },
    spacing: { inRowCm: 60, betweenRowCm: 150, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 14 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "aphid", "squash bug"],
    commonDiseases: ["powdery mildew", "fusarium wilt"],
    harvest: {
      windowDays: { min: 14, max: 28 },
      yieldPerPlant: "3-6 fruits",
      indicators: ["full slip — fruit separates from the stem with a gentle tug; netting raised, sweet aroma"],
      method: "harvest at full slip",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Small enough to trellis with slings; ripeness is all about the slip and the smell.",
    iconKey: "cantaloupe",
    tags: ["sweet", "summer", "heat-loving"],
  },

  // --- Fabaceae ---
  {
    id: "lima_bean",
    commonName: "Lima Bean",
    scientificName: "Phaseolus lunatus",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 5, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 65, max: 85, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 10, betweenRowCm: 60, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 3,
      germinationDays: { min: 7, max: 18 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    commonPests: ["bean beetle", "aphid"],
    commonDiseases: ["downy mildew", "root rot"],
    harvest: {
      windowDays: { min: 21, max: 40 },
      yieldPerPlant: "0.3-0.7 kg",
      indicators: ["pods plump with bulging seeds, still bright"],
      method: "pick at the plump stage for fresh shelling",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Loves heat and resents cold, wet soil — wait until the ground is truly warm to sow.",
    iconKey: "lima_bean",
    tags: ["heat-loving", "protein", "summer"],
  },
  {
    id: "fava_bean",
    commonName: "Fava Bean",
    scientificName: "Vicia faba",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 75, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 90, max: 150 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 60, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -6, max: -4 },
      plantingDepthCm: 5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["stake"],
    commonPests: ["black bean aphid", "pea weevil"],
    commonDiseases: ["chocolate spot", "rust"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.5-1 kg",
      indicators: ["pods filled and glossy; pick young for tender beans"],
      method: "pick from the bottom up as pods fill",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Cold-hardy enough to sow before the last frost; doubles as an early nitrogen-fixing cover crop.",
    iconKey: "fava_bean",
    tags: ["cool-season", "cover-crop", "protein"],
  },
  {
    id: "edamame",
    commonName: "Edamame",
    scientificName: "Glycine max",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 75, max: 95, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 15, max: 30 },
    spacing: { inRowCm: 10, betweenRowCm: 45, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    commonPests: ["bean beetle", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 7, max: 14 },
      yieldPerPlant: "0.3-0.5 kg",
      indicators: ["pods plump and bright green; the whole plant ripens together"],
      method: "pull the whole plant and strip pods",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Vegetable soybean with a tight harvest window — pick the moment the pods fill.",
    iconKey: "edamame",
    tags: ["protein", "summer"],
  },
  {
    id: "runner_bean",
    commonName: "Runner Bean",
    scientificName: "Phaseolus coccineus",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 12,
    gddBaseTempC: 10,
    daysToMaturity: { min: 65, max: 80, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 200, max: 300 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 60, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 4,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["trellis"],
    commonPests: ["black bean aphid", "slug"],
    commonDiseases: ["halo blight", "rust"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "1-2 kg",
      indicators: ["pods 15-20 cm, snapping cleanly before beans swell"],
      method: "pick young and often to keep flowers coming",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Vigorous climber with scarlet, pollinator-friendly flowers — ornamental and edible at once.",
    iconKey: "runner_bean",
    tags: ["ornamental", "climbing", "edible-flower"],
  },

  // --- Brassicaceae ---
  {
    id: "cauliflower",
    commonName: "Cauliflower",
    scientificName: "Brassica oleracea var. botrytis",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 100, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "firm"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N for leaf frame", intervalDays: 14 },
        { atStage: "budding", type: "balanced feed" },
      ],
    },
    commonPests: ["cabbage worm", "aphid", "flea beetle"],
    commonDiseases: ["clubroot", "black rot"],
    harvest: {
      windowDays: { min: 7, max: 14 },
      yieldPerPlant: "1 head, 0.5-1 kg",
      indicators: ["curd firm, white, and compact before it ricing"],
      method: "cut below the head; blanch by tying leaves over the curd",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "hard",
    description:
      "The fussiest brassica — steady moisture and even temperatures are the price of a tight white curd.",
    iconKey: "cauliflower",
    tags: ["cool-season", "heavy-feeder"],
  },
  {
    id: "brussels_sprouts",
    commonName: "Brussels Sprouts",
    scientificName: "Brassica oleracea var. gemmifera",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "firm"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 60, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N for tall frame", intervalDays: 21 },
      ],
    },
    supportStructures: ["stake"],
    commonPests: ["cabbage worm", "aphid"],
    commonDiseases: ["clubroot", "downy mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "0.5-1 kg of sprouts",
      indicators: ["sprouts firm and 2-4 cm; sweeter after a frost"],
      method: "twist off the lowest sprouts first, working upward",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A long-season marathon that pays off in autumn — flavor turns sweet once frost arrives.",
    iconKey: "brussels_sprouts",
    tags: ["cool-season", "frost-sweetened", "long-season"],
  },
  {
    id: "collards",
    commonName: "Collard Greens",
    scientificName: "Brassica oleracea var. acephala",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 6, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 55, max: 75, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 45, max: 75 },
    spacing: { inRowCm: 45, betweenRowCm: 75, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["cabbage worm", "aphid", "flea beetle"],
    commonDiseases: ["black rot", "downy mildew"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "1-2 kg",
      indicators: ["leaves 25 cm+; sweetest after frost"],
      method: "pick lower leaves repeatedly — it keeps producing",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tough, productive, and frost-hardy; a cut-and-come-again staple that shrugs off cold.",
    iconKey: "collards",
    tags: ["cut-and-come-again", "frost-hardy", "southern"],
  },
  {
    id: "bok_choy",
    commonName: "Bok Choy",
    scientificName: "Brassica rapa subsp. chinensis",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 40, max: 55, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "moist"],
    matureHeightCm: { min: 20, max: 30 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 20, betweenRowCm: 30, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 4, max: 8 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 14 },
      ],
    },
    commonPests: ["flea beetle", "aphid", "slug"],
    commonDiseases: ["downy mildew", "clubroot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.3-0.5 kg",
      indicators: ["compact upright bunch before it bolts in heat"],
      method: "cut the whole head at the base, or pick outer stalks",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Fast cool-season green that bolts in heat — grow it in spring and fall, and it tolerates some shade.",
    iconKey: "bok_choy",
    tags: ["fast", "cool-season", "stir-fry", "shade-tolerant"],
  },
  {
    id: "mustard_greens",
    commonName: "Mustard Greens",
    scientificName: "Brassica juncea",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 30, max: 50, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 23, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 2 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 3, max: 7 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["white rust", "downy mildew"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "0.3-0.6 kg",
      indicators: ["young leaves are tender and milder; heat turns them sharp"],
      method: "cut outer leaves, or harvest whole while young",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Peppery, fast, and cold-tolerant — best in spring and fall before the bite turns harsh.",
    iconKey: "mustard_greens",
    tags: ["fast", "spicy", "cool-season"],
  },
  {
    id: "turnip",
    commonName: "Turnip",
    scientificName: "Brassica rapa subsp. rapa",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 35, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "loose"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 10, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 3, max: 10 },
    },
    stageTemplateId: "tmpl_root_fast",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N high-K for roots" },
      ],
    },
    commonPests: ["flea beetle", "root maggot", "aphid"],
    commonDiseases: ["clubroot", "downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.1-0.3 kg per root",
      indicators: ["roots 5-8 cm across; tender before they turn woody"],
      method: "pull by the tops — the greens are edible too",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Quick dual-purpose root — sweet bulbs below, peppery greens above, both best in cool weather.",
    iconKey: "turnip",
    tags: ["fast", "dual-purpose", "cool-season"],
  },

  // --- Apiaceae ---
  {
    id: "parsnip",
    commonName: "Parsnip",
    scientificName: "Pastinaca sativa",
    familyId: "apiaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 100, max: 130, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "deep", "loose", "stone-free"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 10, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 1.5,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "low-N — excess forks the roots" },
        { atStage: "fruiting", type: "low-N high-K" },
      ],
    },
    commonPests: ["carrot rust fly", "aphid"],
    commonDiseases: ["canker", "root rot"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "0.1-0.3 kg",
      indicators: ["crown 4 cm+; flavor turns sweet after hard frost"],
      method: "dig carefully; can be left in the ground through winter",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Slow to germinate and slow to mature, but frost converts its starch to sugar — use fresh seed every year.",
    iconKey: "parsnip",
    tags: ["frost-sweetened", "long-season", "storage"],
  },
  {
    id: "celery",
    commonName: "Celery",
    scientificName: "Apium graveolens",
    familyId: "apiaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 2, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 30, max: 50 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 45, squareFootCount: 2 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 14 },
      ],
    },
    commonPests: ["aphid", "celery leaf miner", "slug"],
    commonDiseases: ["early blight", "fusarium yellows"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "1 bunch",
      indicators: ["stalks 20-30 cm and firm"],
      method: "cut at the base, or pick outer stalks as needed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "hard",
    description:
      "Thirsty and slow — never let it dry out, or the stalks turn stringy and bitter.",
    iconKey: "celery",
    tags: ["thirsty", "long-season"],
  },

  // --- Amaryllidaceae ---
  {
    id: "leek",
    commonName: "Leek",
    scientificName: "Allium ampeloprasum",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 100, max: 140, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -10, max: -8 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["onion thrips", "leek moth"],
    commonDiseases: ["rust", "white rot"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "1 shank",
      indicators: ["shanks 2-3 cm thick; hill soil up to blanch the white"],
      method: "lift with a fork — they hold in the ground through frost",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Cold-hardy allium you harvest all winter; hill the stems as they grow for long blanched shanks.",
    iconKey: "leek",
    tags: ["cold-hardy", "long-season", "blanched"],
  },
  {
    id: "shallot",
    commonName: "Shallot",
    scientificName: "Allium cepa var. aggregatum",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "loose"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 10, max: 15 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -4, max: 0 },
      transplantWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 2,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["onion thrips", "onion fly"],
    commonDiseases: ["white rot", "downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "cluster of 6-10 bulbs",
      indicators: ["tops yellow and topple over"],
      method: "lift the whole cluster and cure for storage",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Plant one set, harvest a cluster — gourmet alliums that store for months once cured.",
    iconKey: "shallot",
    tags: ["gourmet", "storage", "multiplier"],
  },
  {
    id: "scallion",
    commonName: "Scallion",
    scientificName: "Allium fistulosum",
    familyId: "amaryllidaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 5, max: 10 },
    spacing: { inRowCm: 5, betweenRowCm: 15, squareFootCount: 16 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -4, max: 4 },
      transplantWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_allium_bulb",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "light high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["onion thrips"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 bunch",
      indicators: ["1-1.5 cm thick, 15 cm of white-and-green"],
      method: "pull whole, or cut above the base and let it regrow",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Bunching onion that never bulbs — fast, cold-hardy, and willing to regrow after a cut.",
    iconKey: "scallion",
    tags: ["fast", "cut-and-regrow", "cool-season"],
  },

  // --- Asteraceae ---
  {
    id: "zinnia",
    commonName: "Zinnia",
    scientificName: "Zinnia elegans",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 75, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 5.5, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 30, max: 120 },
    matureSpreadCm: { min: 20, max: 40 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "budding", type: "low-N high-P for blooms", intervalDays: 14 },
      ],
    },
    commonPests: ["aphid", "Japanese beetle"],
    commonDiseases: ["powdery mildew", "alternaria leaf spot"],
    harvest: {
      windowDays: { min: 60, max: 90 },
      yieldPerPlant: "many cutting stems",
      indicators: ["petals fully open and the stem stiff below the bloom"],
      method: "cut for the vase and deadhead — more cuts mean more flowers",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Heat-proof cut-flower workhorse that blooms harder the more you pick; a pollinator magnet.",
    iconKey: "zinnia",
    tags: ["pollinator", "cut-flower", "heat-loving", "fast"],
  },
];
