/**
 * §28.2 catalog expansion, tranche 8: cottage-garden and cut-flower annuals,
 * a couple of pseudo-grains and tender legumes, perennial vegetables, and a
 * final run of culinary/medicinal herbs. Same conventions as plants.ts.
 * Reuses existing families and stage templates.
 */

import type { Plant } from "../types/models";

export const plantsTranche8: Plant[] = [
  // --- Asteraceae flowers ---
  {
    id: "bachelor_button",
    commonName: "Bachelor's Button",
    scientificName: "Centaurea cyanus",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 80, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 30, max: 90 },
    matureSpreadCm: { min: 15, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "budding", type: "low-N high-P", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 90 },
      yieldPerPlant: "many cutting stems",
      indicators: ["blue buttons just opening"],
      method: "cut for the vase and deadhead; self-seeds and the petals are edible",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Cornflower — a tough, cold-hardy cottage annual with electric-blue blooms that bees and cut-flower growers adore.",
    iconKey: "bachelor_button",
    tags: ["pollinator", "cut-flower", "self-seeding", "edible-flower"],
  },
  {
    id: "tithonia",
    commonName: "Mexican Sunflower",
    scientificName: "Tithonia rotundifolia",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 45, max: 90 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — lean soil means more flowers" }],
    },
    supportStructures: ["stake"],
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 90 },
      yieldPerPlant: "many vivid blooms",
      indicators: ["brilliant orange daisies on hollow stems"],
      method: "cut and deadhead; a magnet for butterflies and monarchs",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A towering, heat-loving annual that blazes orange until frost and pulls in butterflies like nothing else.",
    iconKey: "tithonia",
    tags: ["pollinator", "butterfly", "heat-loving", "cut-flower"],
  },
  {
    id: "strawflower",
    commonName: "Strawflower",
    scientificName: "Xerochrysum bracteatum",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 30, max: 90 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "budding", type: "low-N high-P", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 60, max: 90 },
      yieldPerPlant: "many everlasting blooms",
      indicators: ["papery bracts; cut before fully open for drying"],
      method: "cut for fresh or hang to dry — the color holds for months",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "The classic 'everlasting' — crisp, papery petals in hot colors that dry beautifully for winter bouquets.",
    iconKey: "strawflower",
    tags: ["everlasting", "cut-flower", "dried", "drought-tolerant"],
  },
  {
    id: "echinacea",
    commonName: "Coneflower",
    scientificName: "Echinacea purpurea",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "budding", type: "low-N high-P", intervalDays: 30 },
      ],
    },
    commonPests: ["aphid", "Japanese beetle"],
    commonDiseases: ["aster yellows", "powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "many blooms",
      indicators: ["purple daisies with raised copper cones"],
      method: "cut for the vase; leave late seedheads for goldfinches",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A drought-tough native prairie perennial — long-blooming, pollinator-packed, and often slow to flower until its second year.",
    iconKey: "echinacea",
    tags: ["pollinator", "perennial", "native", "drought-tolerant"],
  },
  {
    id: "dahlia",
    commonName: "Dahlia",
    scientificName: "Dahlia pinnata",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "perennial",
    hardinessZones: { min: 8, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "tender",
    waterloggingSensitivity: "high",
    seedViabilityYears: 1,
    minSoilTempC: 15,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 45, max: 150 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["transplant"],
    sowRules: {
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 10,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "budding", type: "low-N high-K", intervalDays: 14 },
      ],
    },
    supportStructures: ["stake"],
    commonPests: ["earwig", "slug", "aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "many cutting blooms",
      indicators: ["blooms fully open — they don't open further once cut"],
      method: "cut and deadhead; lift and store tubers before hard frost in cold zones",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Grown from a tender tuber for show-stopping blooms in every size; the more you cut, the more it flowers.",
    iconKey: "dahlia",
    tags: ["cut-flower", "tuber", "showy", "tender"],
  },
  {
    id: "china_aster",
    commonName: "China Aster",
    scientificName: "Callistephus chinensis",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 75 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 10, max: 14 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "budding", type: "low-N high-P", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "aster leafhopper"],
    commonDiseases: ["aster yellows", "fusarium wilt"],
    harvest: {
      windowDays: { min: 45, max: 75 },
      yieldPerPlant: "many double blooms",
      indicators: ["full double flowers in a single late-summer flush"],
      method: "cut for the vase; rotate beds yearly, as it's wilt-prone",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A showy late-summer cut-flower annual in rich jewel tones; rotate its bed each year to dodge soil-borne wilt.",
    iconKey: "china_aster",
    tags: ["cut-flower", "annual", "showy"],
  },
  {
    id: "safflower",
    commonName: "Safflower",
    scientificName: "Carthamus tinctorius",
    familyId: "asteraceae",
    category: "flower",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 10 },
    heatTolerance: "high",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 110, max: 140, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "deep"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 35, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 10, max: 15 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "budding", type: "low-N feed" },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot", "rust"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "petals and seed",
      indicators: ["thistle-like orange flowers — a saffron-color substitute and dye"],
      method: "cut flowers gloved (they're spiny); a deep taproot makes it drought-proof",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A spiny, drought-defying thistle grown for golden dye-petals and oil seed; needs a long, dry-finishing season.",
    iconKey: "safflower",
    tags: ["drought-tolerant", "dye-plant", "long-season", "spiny"],
  },

  // --- Grain / tender legumes ---
  {
    id: "quinoa",
    commonName: "Quinoa",
    scientificName: "Chenopodium quinoa",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 4, max: 10 },
    },
    stageTemplateId: "tmpl_flower_annual",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "leaf miner"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.1-0.3 kg of seed",
      indicators: ["seed heads dry and seeds thresh off with a rub of the hand"],
      method: "cut heads, dry, thresh, then rinse the bitter saponin coating",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A protein-rich Andean pseudo-grain that prefers cool, dry conditions; the young leaves are edible like spinach too.",
    iconKey: "quinoa",
    tags: ["grain", "pseudocereal", "drought-tolerant", "cool-tolerant"],
  },
  {
    id: "peanut",
    commonName: "Peanut",
    scientificName: "Arachis hypogaea",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 6, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 18,
    optSoilTempC: { min: 24, max: 32 },
    gddBaseTempC: 10,
    daysToMaturity: { min: 120, max: 150, from: "sow" },
    sun: "full",
    sunHoursMin: 8,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 5.8, max: 6.5 },
    soilPreference: ["well-drained", "sandy", "loose"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 15, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 4,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "none — fixes its own nitrogen; add gypsum at pegging" },
      ],
    },
    commonPests: ["aphid", "thrips"],
    commonDiseases: ["leaf spot", "white mold"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.2-0.5 kg",
      indicators: ["foliage yellows; pods filled out underground"],
      method: "lift the whole plant and cure the pods on the vine",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Flowers above ground, then 'pegs' down to ripen pods in the soil — needs heat, sandy ground, and a long season.",
    iconKey: "peanut",
    tags: ["heat-loving", "long-season", "underground-pods", "protein"],
  },
  {
    id: "hyacinth_bean",
    commonName: "Hyacinth Bean",
    scientificName: "Lablab purpureus",
    familyId: "fabaceae",
    category: "flower",
    lifecycle: "perennial",
    hardinessZones: { min: 9, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 70, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 240, max: 360 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 20, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 21 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid", "bean beetle"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "ornamental pods and flowers",
      indicators: ["glossy purple pods and lilac flowers cloak the vine"],
      method: "grow for show; only young pods are edible cooked — mature seeds are toxic raw",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A fast, gorgeous purple-podded climber for screening and pollinators; striking enough to grow for looks alone.",
    iconKey: "hyacinth_bean",
    tags: ["ornamental", "climbing", "pollinator"],
  },

  // --- Perennial vegetables / brassicas ---
  {
    id: "purple_sprouting_broccoli",
    commonName: "Purple Sprouting Broccoli",
    scientificName: "Brassica oleracea var. italica",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 6, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 150, max: 220, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "firm"],
    matureHeightCm: { min: 60, max: 90 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: 8, max: 12 },
      transplantWeeksFromLastFrost: { min: 14, max: 18 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
        { atStage: "budding", type: "balanced feed" },
      ],
    },
    supportStructures: ["stake"],
    commonPests: ["cabbage worm", "aphid"],
    commonDiseases: ["clubroot", "downy mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "many small spears",
      indicators: ["clusters of tender purple spears in early spring after overwintering"],
      method: "cut spears repeatedly — picking spurs more side shoots",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Sown in summer to overwinter and crop the following spring — a hardy hungry-gap treat of sweet purple spears.",
    iconKey: "purple_sprouting_broccoli",
    tags: ["overwintering", "frost-hardy", "cut-and-come-again", "spring-crop"],
  },
  {
    id: "sea_kale",
    commonName: "Sea Kale",
    scientificName: "Crambe maritima",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 120, max: 160, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.5, max: 7.5 },
    soilPreference: ["well-drained", "sandy", "deep"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 14, max: 28 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["flea beetle", "cabbage worm"],
    commonDiseases: ["clubroot"],
    harvest: {
      windowDays: { min: 21, max: 45 },
      yieldPerPlant: "blanched spring shoots",
      indicators: ["force tender pale shoots under a pot in early spring"],
      method: "cover crowns to blanch, then cut shoots like asparagus; harvest from year two",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A long-lived coastal perennial whose blanched spring shoots are a delicacy; patient establishment, then decades of crops.",
    iconKey: "sea_kale",
    tags: ["perennial", "blanched", "coastal", "heritage"],
  },
  {
    id: "winter_melon",
    commonName: "Winter Melon",
    scientificName: "Benincasa hispida",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 8, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 130, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 240, max: 360 },
    spacing: { inRowCm: 90, betweenRowCm: 240, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 21 },
      ],
    },
    commonPests: ["squash bug", "cucumber beetle"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "2-4 fruits",
      indicators: ["big fruit with a chalky white wax bloom on the skin"],
      method: "cut with a handle; the waxy coating lets it store for months",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Wax gourd — a big, mild tropical squash whose waxy rind keeps it storing through winter; needs a long, hot season.",
    iconKey: "winter_melon",
    tags: ["storage", "asian", "heat-loving", "sprawling"],
  },

  // --- Herbs ---
  {
    id: "anise",
    commonName: "Anise",
    scientificName: "Pimpinella anisum",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 100, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "light"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "seed heads",
      indicators: ["umbels ripen gray-brown"],
      method: "cut heads, dry, and thresh for the licorice-flavored seed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The true licorice spice — a tender annual that resents transplanting, so direct-sow and give it a long warm spell to ripen seed.",
    iconKey: "anise",
    tags: ["licorice", "seed-spice", "warm-season"],
  },
  {
    id: "angelica",
    commonName: "Angelica",
    scientificName: "Angelica archangelica",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "biennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "medium",
    waterMmPerWeek: { min: 30, max: 45 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 120, max: 200 },
    matureSpreadCm: { min: 60, max: 90 },
    spacing: { inRowCm: 60, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 21, max: 35 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid", "leaf miner"],
    commonDiseases: ["crown rot"],
    harvest: {
      windowDays: { min: 60, max: 150 },
      yieldPerPlant: "candied stems, leaves, and seed",
      indicators: ["tender young stems for candying; aromatic seed in year two"],
      method: "cut young stems; the plant dies after it flowers and seeds",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "A statuesque biennial for damp, shaded corners — celery-scented stems traditionally candied; sow fresh seed, which is short-lived.",
    iconKey: "angelica",
    tags: ["biennial", "aromatic", "shade-tolerant", "large"],
  },
  {
    id: "winter_savory",
    commonName: "Winter Savory",
    scientificName: "Satureja montana",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 5, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "lean", "gritty"],
    matureHeightCm: { min: 15, max: 40 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — lean soil sharpens flavor" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 120, max: 200 },
      yieldPerPlant: "year-round sprigs",
      indicators: ["peppery, semi-evergreen leaves — sharper than summer savory"],
      method: "snip sprigs as needed; shear lightly to keep it bushy",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "The hardy, woody savory — a low Mediterranean sub-shrub that holds its peppery leaves into winter.",
    iconKey: "winter_savory",
    tags: ["mediterranean", "perennial", "drought-tolerant", "evergreen"],
  },
  {
    id: "hyssop",
    commonName: "Hyssop",
    scientificName: "Hyssopus officinalis",
    familyId: "lamiaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 13,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed", intervalDays: 45 },
      ],
    },
    commonPests: ["aphid"],
    commonDiseases: ["root rot"],
    harvest: {
      windowDays: { min: 90, max: 150 },
      yieldPerPlant: "leaves and flower spikes",
      indicators: ["spikes of blue flowers; bitter-minty leaves"],
      method: "snip leaves and flowers; a strong bee and butterfly draw",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "An old-world evergreen herb with intense blue flower spikes — drought-tough, pollinator-rich, and good as a low hedge.",
    iconKey: "hyssop",
    tags: ["pollinator", "mediterranean", "perennial", "drought-tolerant"],
  },
  {
    id: "stevia",
    commonName: "Stevia",
    scientificName: "Stevia rebaudiana",
    familyId: "asteraceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 9, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 110, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "vegetative", type: "light feed", intervalDays: 30 },
      ],
    },
    commonPests: ["aphid", "whitefly"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 60, max: 120 },
      yieldPerPlant: "sweet leaves",
      indicators: ["leaves are sweetest just before flowering"],
      method: "strip leaves and dry them for a natural sweetener",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The sugar-leaf herb — intensely sweet foliage from a tender perennial best grown in a pot you can overwinter indoors.",
    iconKey: "stevia",
    tags: ["sweetener", "tender-perennial", "container-friendly"],
  },
  {
    id: "yarrow",
    commonName: "Yarrow",
    scientificName: "Achillea millefolium",
    familyId: "asteraceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "high",
    frostTolerance: "hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 5.5, max: 7.5 },
    soilPreference: ["well-drained", "lean"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 30, max: 60 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.1,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — lean soil keeps stems sturdy" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 180 },
      yieldPerPlant: "many flat flower clusters",
      indicators: ["flat-topped flower heads; ferny aromatic foliage"],
      method: "cut for fresh or dried arrangements; draws beneficial insects",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A tough, drought-proof native perennial whose flat flower heads feed pollinators and predatory insects alike.",
    iconKey: "yarrow",
    tags: ["pollinator", "perennial", "drought-tolerant", "native"],
  },
  {
    id: "feverfew",
    commonName: "Feverfew",
    scientificName: "Tanacetum parthenium",
    familyId: "asteraceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 90, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 45, max: 90 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 30, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      directSowWeeksFromLastFrost: { min: 0, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.1,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost at planting" }],
    },
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 90, max: 150 },
      yieldPerPlant: "flowers and leaves",
      indicators: ["small white daisies with yellow centers; pungent foliage"],
      method: "cut flowers and leaves; it self-seeds prolifically",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A cheerful, daisy-flowered cottage perennial that reseeds itself everywhere — traditionally a medicinal, and a tidy edger.",
    iconKey: "feverfew",
    tags: ["pollinator", "perennial", "self-seeding", "medicinal"],
  },

  // --- Stem-lettuce & leaf celery ---
  {
    id: "celtuce",
    commonName: "Celtuce",
    scientificName: "Lactuca sativa var. augustana",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 4,
    gddBaseTempC: 5,
    daysToMaturity: { min: 75, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 25, max: 35 },
    spacing: { inRowCm: 25, betweenRowCm: 35, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -5, max: -3 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "slug"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "1 thick stem",
      indicators: ["grown for its crisp, swollen stem; harvest before it flowers"],
      method: "peel and eat the stem raw or cooked; young leaves are edible too",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Stem lettuce — grown for a crunchy, mild celery-like stalk rather than its leaves; a cool-season novelty.",
    iconKey: "celtuce",
    tags: ["stem-lettuce", "asian", "cool-season", "unusual"],
  },
  {
    id: "cutting_celery",
    commonName: "Cutting Celery",
    scientificName: "Apium graveolens var. secalinum",
    familyId: "apiaceae",
    category: "herb",
    lifecycle: "biennial",
    hardinessZones: { min: 2, max: 10 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 3,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 30, max: 45 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["rich", "moisture-retentive"],
    matureHeightCm: { min: 30, max: 60 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 14, max: 21 },
    },
    stageTemplateId: "tmpl_herb_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "celery leaf miner"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 60, max: 150 },
      yieldPerPlant: "ongoing leafy stalks",
      indicators: ["slender, intensely-flavored stalks and leaves"],
      method: "snip outer stalks as needed — far easier than blanched stalk celery",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Leaf celery grown for punchy stalks and foliage rather than fat ribs — tougher and far less fussy than its stalk-celery cousin.",
    iconKey: "cutting_celery",
    tags: ["celery-flavor", "cut-and-come-again", "shade-tolerant", "easy"],
  },
];
