/**
 * §28.2 catalog expansion, tranche 6: more vegetables — peas and exotic
 * legumes, vining cucurbits, Italian/Asian brassicas, chicory-family roots,
 * heat- and cold-hardy greens, and heading lettuces. Same conventions as
 * plants.ts. Reuses existing families and stage templates.
 */

import type { Plant } from "../types/models";

export const plantsTranche6: Plant[] = [
  // --- Legumes ---
  {
    id: "snow_pea",
    commonName: "Snow Pea",
    scientificName: "Pisum sativum var. saccharatum",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 55, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 5, betweenRowCm: 45, squareFootCount: 8 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -6, max: -2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid", "pea weevil"],
    commonDiseases: ["powdery mildew", "fusarium wilt"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.3-0.5 kg",
      indicators: ["flat pods harvested before the peas swell"],
      method: "pick young and often to keep pods coming",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Flat, sweet edible-pod pea for cool weather — sow as early as the soil can be worked.",
    iconKey: "snow_pea",
    tags: ["cool-season", "edible-pod", "climbing"],
  },
  {
    id: "shelling_pea",
    commonName: "Shelling Pea",
    scientificName: "Pisum sativum",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 60, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "loamy"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 5, betweenRowCm: 45, squareFootCount: 8 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -6, max: -2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid", "pea weevil"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 7, max: 21 },
      yieldPerPlant: "0.2-0.4 kg",
      indicators: ["pods plump and rounded, peas sweet before they turn starchy"],
      method: "pick as pods fill; sugars fade fast after picking",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "The classic garden pea for shelling — a fleeting, sweet spring treat best eaten the day it's picked.",
    iconKey: "shelling_pea",
    tags: ["cool-season", "shelling", "climbing"],
  },
  {
    id: "yardlong_bean",
    commonName: "Yardlong Bean",
    scientificName: "Vigna unguiculata subsp. sesquipedalis",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 7, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 60, max: 80, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "warm"],
    matureHeightCm: { min: 180, max: 300 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 60, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid", "bean beetle"],
    commonDiseases: ["rust"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "1-2 kg",
      indicators: ["pods 30-45 cm and pencil-thick, before the seeds bulge"],
      method: "pick young and often — they grow fast in heat",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Heat-loving climbing cowpea with absurdly long, tender pods — a stir-fry staple that thrives where common beans sulk.",
    iconKey: "yardlong_bean",
    tags: ["heat-loving", "climbing", "asian"],
  },
  {
    id: "lentil",
    commonName: "Lentil",
    scientificName: "Lens culinaris",
    familyId: "fabaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "high",
    seedViabilityYears: 3,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 80, max: 110, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 15, max: 25 },
    soilPh: { min: 6.0, max: 8.0 },
    soilPreference: ["well-drained", "sandy"],
    matureHeightCm: { min: 30, max: 50 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 5, betweenRowCm: 30, squareFootCount: 8 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 10, max: 14 },
    },
    stageTemplateId: "tmpl_legume",
    fertilization: {
      schedule: [{ atStage: "planted", type: "none — fixes its own nitrogen" }],
    },
    commonPests: ["aphid", "weevil"],
    commonDiseases: ["ascochyta blight", "root rot"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "0.1-0.2 kg",
      indicators: ["lower pods dry and rattly"],
      method: "pull whole plants, dry, then thresh out the seed",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Drought-tough dry pulse for a long, dry-finishing season — modest yields but improves the soil as it grows.",
    iconKey: "lentil",
    tags: ["drought-tolerant", "dry-pulse", "protein"],
  },

  // --- Vining cucurbits ---
  {
    id: "bitter_melon",
    commonName: "Bitter Melon",
    scientificName: "Momordica charantia",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 9, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 3,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 80, max: 100, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 6.8 },
    soilPreference: ["well-drained", "rich", "warm"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 180, max: 300 },
    spacing: { inRowCm: 45, betweenRowCm: 120, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -3, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 7, max: 21 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 21 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "fruit fly"],
    commonDiseases: ["powdery mildew", "downy mildew"],
    harvest: {
      windowDays: { min: 30, max: 60 },
      yieldPerPlant: "many fruits",
      indicators: ["light green and warty, before it turns orange and splits"],
      method: "cut young — bitterness intensifies as fruit matures",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Vigorous tropical climber grown for its warty, bracing fruit; needs heat and a sturdy trellis.",
    iconKey: "bitter_melon",
    tags: ["heat-loving", "asian", "climbing"],
  },
  {
    id: "luffa",
    commonName: "Luffa",
    scientificName: "Luffa aegyptiaca",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 7, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 90, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 240, max: 360 },
    spacing: { inRowCm: 60, betweenRowCm: 180, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 2, max: 3 },
      plantingDepthCm: 2.5,
      germinationDays: { min: 7, max: 21 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 21 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["cucumber beetle", "squash bug"],
    commonDiseases: ["powdery mildew", "mosaic virus"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "several fruits",
      indicators: ["eat young like zucchini, or let it brown on the vine for sponges"],
      method: "cut young for food, or leave to dry then peel for a loofah",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Long-season vine that's edible young and becomes a natural sponge when mature — needs a strong trellis and a long, hot summer.",
    iconKey: "luffa",
    tags: ["heat-loving", "sponge", "climbing", "long-season"],
  },
  {
    id: "cucamelon",
    commonName: "Cucamelon",
    scientificName: "Melothria scabra",
    familyId: "cucurbitaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "high",
    frostTolerance: "tender",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 18,
    gddBaseTempC: 10,
    daysToMaturity: { min: 65, max: 75, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 150, max: 240 },
    spacing: { inRowCm: 30, betweenRowCm: 90, squareFootCount: 1 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -4, max: -2 },
      directSowWeeksFromLastFrost: { min: 1, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 1,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_fruiting_vine",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "compost-amended bed" },
        { atStage: "flowering", type: "balanced liquid feed", intervalDays: 21 },
      ],
    },
    supportStructures: ["trellis"],
    commonPests: ["aphid"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "many tiny fruits",
      indicators: ["grape-sized and firm; pick before they soften"],
      method: "pick frequently — they hide under the dainty foliage",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Grape-sized 'mouse melons' that taste of cucumber with a citrus tang — a tough, drought-tolerant novelty vine.",
    iconKey: "cucamelon",
    tags: ["novelty", "climbing", "prolific", "drought-tolerant"],
  },

  // --- Italian / Asian brassicas ---
  {
    id: "rapini",
    commonName: "Broccoli Rabe",
    scientificName: "Brassica rapa subsp. ruvo",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 40, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 15, max: 25 },
    spacing: { inRowCm: 15, betweenRowCm: 30, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 14 },
      ],
    },
    commonPests: ["flea beetle", "cabbage worm"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 30 },
      yieldPerPlant: "bunches of shoots",
      indicators: ["harvest at the bud stage, before the yellow flowers open"],
      method: "cut leafy stalks with their buds; pleasantly bitter",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Fast, pleasantly bitter Italian green grown for its budded shoots; bolts quickly, so harvest promptly.",
    iconKey: "rapini",
    tags: ["fast", "bitter-green", "italian"],
  },
  {
    id: "romanesco",
    commonName: "Romanesco",
    scientificName: "Brassica oleracea var. botrytis",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 75, max: 100, from: "transplant" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "high",
    waterMmPerWeek: { min: 25, max: 40 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich", "firm"],
    matureHeightCm: { min: 45, max: 75 },
    matureSpreadCm: { min: 45, max: 60 },
    spacing: { inRowCm: 45, betweenRowCm: 60, squareFootCount: 1 },
    plantingMethods: ["indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -6, max: -4 },
      transplantWeeksFromLastFrost: { min: 2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N for leaf frame", intervalDays: 14 },
        { atStage: "budding", type: "balanced feed" },
      ],
    },
    commonPests: ["cabbage worm", "aphid"],
    commonDiseases: ["clubroot", "black rot"],
    harvest: {
      windowDays: { min: 7, max: 14 },
      yieldPerPlant: "1 head",
      indicators: ["lime-green fractal spirals firm and tight"],
      method: "cut below the head once it sizes up",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "hard",
    description:
      "The mesmerizing fractal cauliflower — as demanding as its cousin, rewarding steady moisture and cool weather with a stunning head.",
    iconKey: "romanesco",
    tags: ["fractal", "cool-season", "gourmet"],
  },
  {
    id: "gai_lan",
    commonName: "Chinese Broccoli",
    scientificName: "Brassica oleracea var. alboglabra",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 20, betweenRowCm: 35, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 1,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_brassica_heading",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 14 },
      ],
    },
    commonPests: ["flea beetle", "cabbage worm"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "main stalk plus side shoots",
      indicators: ["thick stems with buds, before the flowers open"],
      method: "cut the main stalk; side shoots keep coming",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Stem broccoli grown for its sweet, thick stalks and buds — fast, productive, and cut-and-come-again.",
    iconKey: "gai_lan",
    tags: ["asian-greens", "stem-broccoli", "cut-and-come-again"],
  },
  {
    id: "watercress",
    commonName: "Watercress",
    scientificName: "Nasturtium officinale",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "low",
    seedViabilityYears: 5,
    minSoilTempC: 10,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 60, from: "sow" },
    sun: "partial",
    sunHoursMin: 4,
    waterNeed: "high",
    waterMmPerWeek: { min: 40, max: 60 },
    soilPh: { min: 6.5, max: 7.5 },
    soilPreference: ["constantly moist", "rich"],
    matureHeightCm: { min: 15, max: 30 },
    matureSpreadCm: { min: 20, max: 40 },
    spacing: { inRowCm: 15, betweenRowCm: 20, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: 0, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "light feed", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "snail"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 30, max: 120 },
      yieldPerPlant: "frequent cuttings",
      indicators: ["tender peppery sprigs; keep it constantly wet"],
      method: "snip tips often; grow at a pond edge or in a wet container",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Peppery semi-aquatic green that demands constant moisture and a little shade; thrives where most crops would rot.",
    iconKey: "watercress",
    tags: ["aquatic", "peppery", "shade-tolerant", "perennial"],
  },
  {
    id: "komatsuna",
    commonName: "Komatsuna",
    scientificName: "Brassica rapa var. perviridis",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 35, max: 50, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 25, max: 40 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 8 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 4, max: 8 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["downy mildew"],
    harvest: {
      windowDays: { min: 21, max: 60 },
      yieldPerPlant: "repeated cuttings",
      indicators: ["mild leaves 15-25 cm; very cold-tolerant"],
      method: "cut outer leaves or harvest the whole plant young",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Fast, forgiving Japanese mustard spinach that shrugs off both heat and hard frost — a near year-round green.",
    iconKey: "komatsuna",
    tags: ["fast", "cold-hardy", "asian-greens", "cut-and-come-again"],
  },
  {
    id: "cress",
    commonName: "Garden Cress",
    scientificName: "Lepidium sativum",
    familyId: "brassicaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 5,
    gddBaseTempC: 5,
    daysToMaturity: { min: 15, max: 30, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["moist", "rich"],
    matureHeightCm: { min: 15, max: 30 },
    matureSpreadCm: { min: 5, max: 10 },
    spacing: { inRowCm: 5, betweenRowCm: 15, squareFootCount: 16 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 8 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 3, max: 7 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [{ atStage: "planted", type: "light compost — it's quick and undemanding" }],
    },
    commonPests: ["flea beetle", "aphid"],
    commonDiseases: ["damping off"],
    harvest: {
      windowDays: { min: 7, max: 21 },
      yieldPerPlant: "microgreen to baby-leaf",
      indicators: ["snip at 5-10 cm; peppery and tender"],
      method: "cut with scissors; succession-sow every week",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "About the fastest crop you can grow — peppery sprigs ready within weeks, perfect for impatient gardeners and windowsills.",
    iconKey: "cress",
    tags: ["fast", "peppery", "microgreen", "cool-season"],
  },

  // --- Chicory-family roots ---
  {
    id: "salsify",
    commonName: "Salsify",
    scientificName: "Tragopogon porrifolius",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "low",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 110, max: 150, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 20, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained", "deep", "loose", "stone-free"],
    matureHeightCm: { min: 60, max: 120 },
    matureSpreadCm: { min: 15, max: 20 },
    spacing: { inRowCm: 8, betweenRowCm: 30, squareFootCount: 9 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      plantingDepthCm: 1.5,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "low-N — rich soil forks the roots" },
        { atStage: "fruiting", type: "low-N high-K" },
      ],
    },
    commonPests: ["carrot rust fly", "aphid"],
    commonDiseases: ["white blister"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "0.1-0.2 kg",
      indicators: ["slender roots with a delicate oyster flavor; sweeter after frost"],
      method: "dig carefully; holds in the ground over winter",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "The 'oyster plant' — a slow, frost-sweetened root for deep, stone-free soil; use fresh seed for good germination.",
    iconKey: "salsify",
    tags: ["oyster-flavor", "long-season", "frost-sweetened"],
  },
  {
    id: "burdock",
    commonName: "Burdock",
    scientificName: "Arctium lappa",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 100, max: 120, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["deep", "loose", "sandy"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 15, betweenRowCm: 45, squareFootCount: 1 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 1.5,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_root_slow",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "fruiting", type: "low-N high-K" },
      ],
    },
    commonPests: ["aphid", "root-knot nematode"],
    commonDiseases: ["powdery mildew"],
    harvest: {
      windowDays: { min: 30, max: 90 },
      yieldPerPlant: "0.2-0.4 kg",
      indicators: ["long, slender taproots driving up to 60 cm deep"],
      method: "dig deep — really deep, loose soil is essential",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "moderate",
    description:
      "Gobo — the earthy, crisp Japanese root with a famously long taproot that needs deep, loose ground to grow straight.",
    iconKey: "burdock",
    tags: ["long-root", "asian", "deep-soil", "earthy"],
  },

  // --- Amaranth-family greens ---
  {
    id: "orach",
    commonName: "Orach",
    scientificName: "Atriplex hortensis",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 4, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 2,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 40, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "low",
    waterMmPerWeek: { min: 20, max: 30 },
    soilPh: { min: 6.0, max: 7.5 },
    soilPreference: ["well-drained"],
    matureHeightCm: { min: 90, max: 180 },
    matureSpreadCm: { min: 30, max: 45 },
    spacing: { inRowCm: 20, betweenRowCm: 35, squareFootCount: 2 },
    plantingMethods: ["direct_sow"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      plantingDepthCm: 1,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "leaf miner"],
    commonDiseases: ["leaf spot"],
    harvest: {
      windowDays: { min: 30, max: 70 },
      yieldPerPlant: "ongoing greens",
      indicators: ["young leaves before flowering; a heat-tolerant spinach stand-in"],
      method: "pinch tips; remove flower spikes to prolong leafing",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Tall, often ruby-leaved 'mountain spinach' that keeps producing in heat that bolts true spinach — and looks ornamental doing it.",
    iconKey: "orach",
    tags: ["heat-tolerant", "spinach-substitute", "ornamental", "self-seeding"],
  },
  {
    id: "spinach_beet",
    commonName: "Perpetual Spinach",
    scientificName: "Beta vulgaris subsp. cicla",
    familyId: "amaranthaceae",
    category: "vegetable",
    lifecycle: "biennial",
    hardinessZones: { min: 3, max: 10 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 50, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 45 },
    matureSpreadCm: { min: 25, max: 35 },
    spacing: { inRowCm: 20, betweenRowCm: 35, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "transplant"],
    sowRules: {
      directSowWeeksFromLastFrost: { min: -2, max: 6 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 2,
      germinationDays: { min: 7, max: 14 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["leaf miner", "aphid"],
    commonDiseases: ["cercospora leaf spot", "downy mildew"],
    harvest: {
      windowDays: { min: 90, max: 200 },
      yieldPerPlant: "continuous greens",
      indicators: ["tender leaf-beet leaves; rarely bolts"],
      method: "pick outer leaves continuously over a long season",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A leaf beet that crops like spinach but won't bolt — one sowing supplies tender greens for many months.",
    iconKey: "spinach_beet",
    tags: ["bolt-resistant", "cut-and-come-again", "cold-hardy", "shade-tolerant"],
  },

  // --- Allium herb ---
  {
    id: "garlic_chives",
    commonName: "Garlic Chives",
    scientificName: "Allium tuberosum",
    familyId: "amaryllidaceae",
    category: "herb",
    lifecycle: "perennial",
    hardinessZones: { min: 3, max: 9 },
    heatTolerance: "medium",
    frostTolerance: "hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 1,
    minSoilTempC: 7,
    gddBaseTempC: 5,
    daysToMaturity: { min: 80, max: 90, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 30, max: 50 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 15, betweenRowCm: 25, squareFootCount: 4 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -8, max: -6 },
      directSowWeeksFromLastFrost: { min: -2, max: 2 },
      transplantWeeksFromLastFrost: { min: 1, max: 2 },
      plantingDepthCm: 0.6,
      germinationDays: { min: 10, max: 21 },
    },
    stageTemplateId: "tmpl_herb_perennial",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "light compost at planting" },
        { atStage: "vegetative", type: "light feed after cutting", intervalDays: 30 },
      ],
    },
    commonPests: ["onion thrips"],
    commonDiseases: ["downy mildew", "rust"],
    harvest: {
      windowDays: { min: 120, max: 200 },
      yieldPerPlant: "frequent cuttings",
      indicators: ["flat garlicky leaves; edible white star flowers in late summer"],
      method: "snip leaves near the base; deadhead to limit self-seeding",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "A tough perennial allium with flat, mildly garlicky leaves and pollinator-friendly white flowers — give it the chive treatment.",
    iconKey: "garlic_chives",
    tags: ["perennial", "garlicky", "pollinator", "cut-and-regrow"],
  },

  // --- Heading lettuces ---
  {
    id: "romaine_lettuce",
    commonName: "Romaine Lettuce",
    scientificName: "Lactuca sativa var. longifolia",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 4,
    gddBaseTempC: 5,
    daysToMaturity: { min: 55, max: 70, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 25, max: 35 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -5, max: -3 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "slug", "cutworm"],
    commonDiseases: ["downy mildew", "bottom rot"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 head",
      indicators: ["upright, crisp heads that hold longer than loose-leaf"],
      method: "cut at the base, or pick outer leaves as you go",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Crisp upright lettuce that stands heat a touch better than most; some afternoon shade staves off summer bolting.",
    iconKey: "romaine_lettuce",
    tags: ["crisp", "cool-season", "heading", "shade-tolerant"],
  },
  {
    id: "butterhead_lettuce",
    commonName: "Butterhead Lettuce",
    scientificName: "Lactuca sativa var. capitata",
    familyId: "asteraceae",
    category: "vegetable",
    lifecycle: "annual",
    hardinessZones: { min: 2, max: 11 },
    heatTolerance: "low",
    frostTolerance: "half_hardy",
    waterloggingSensitivity: "medium",
    seedViabilityYears: 4,
    minSoilTempC: 4,
    gddBaseTempC: 5,
    daysToMaturity: { min: 45, max: 60, from: "sow" },
    sun: "full",
    sunHoursMin: 6,
    waterNeed: "medium",
    waterMmPerWeek: { min: 25, max: 35 },
    soilPh: { min: 6.0, max: 7.0 },
    soilPreference: ["well-drained", "rich"],
    matureHeightCm: { min: 15, max: 25 },
    matureSpreadCm: { min: 20, max: 30 },
    spacing: { inRowCm: 25, betweenRowCm: 30, squareFootCount: 2 },
    plantingMethods: ["direct_sow", "indoor_start", "transplant"],
    sowRules: {
      indoorStartWeeksFromLastFrost: { min: -5, max: -3 },
      directSowWeeksFromLastFrost: { min: -2, max: 4 },
      transplantWeeksFromLastFrost: { min: 1, max: 3 },
      plantingDepthCm: 0.3,
      germinationDays: { min: 5, max: 10 },
    },
    stageTemplateId: "tmpl_leafy",
    fertilization: {
      schedule: [
        { atStage: "planted", type: "balanced 10-10-10" },
        { atStage: "vegetative", type: "high-N side-dress", intervalDays: 21 },
      ],
    },
    commonPests: ["aphid", "slug"],
    commonDiseases: ["downy mildew", "tipburn"],
    harvest: {
      windowDays: { min: 14, max: 40 },
      yieldPerPlant: "1 head",
      indicators: ["loose, tender heads with a soft buttery heart"],
      method: "cut the whole head, or pick outer leaves over time",
    },
    varietalIds: [],
    recipeIds: [],
    difficulty: "easy",
    description:
      "Soft, sweet loose-heading lettuce that's quick and forgiving; give it shade and water to delay bolting in heat.",
    iconKey: "butterhead_lettuce",
    tags: ["tender", "cool-season", "heading", "shade-tolerant"],
  },
];
