/**
 * Stage sprite pixel maps (§13.5, §21.4). Multiple shape families so
 * different plant types get distinct silhouettes. Characters are palette
 * slots — a single map renders per-category (and per-plant accent) variants:
 *
 *   .  transparent      s  stem          f  accent (fruit/bloom)
 *   m  soil light       l  leaf          F  accent shade
 *   M  soil dark        L  leaf shade    y  dry/senescent
 *   w  wood/stub
 */

import type { StageKey } from "../types/models";

export type PixelMap = readonly string[];

/** Sprite grid resolution — all maps are RES×RES. */
export const SPRITE_RES = 32;

export type SpriteShape =
  | "bush"
  | "root"
  | "vine"
  | "tall"
  | "leafy"
  | "herb"
  | "flower"
  | "bulb"
  | "climbing"
  | "grass"
  | "cob"
  | "head"
  | "gourd"
  | "crown"
  | "berry";

export const SHAPE_LABELS: Record<SpriteShape, string> = {
  bush: "Bush",
  root: "Root crop",
  vine: "Vine / Trailing",
  tall: "Tall / Upright",
  leafy: "Leafy / Rosette",
  herb: "Herb",
  flower: "Flower",
  bulb: "Bulb",
  climbing: "Climbing / Trellis",
  grass: "Grass / Grain",
  cob: "Cob / Ear",
  head: "Head / Ball",
  gourd: "Gourd / Ground fruit",
  crown: "Crown / Floret",
  berry: "Berry bush",
};

const SOIL = [
  "....mmmmmmmm....",
  "..mmMMMMMMMMmm..",
  ".mMMMMMMMMMMMMm.",
  "................",
] as const;

function withSoil(top: readonly string[]): PixelMap {
  return [...top, ...SOIL];
}

function upscale2x(map: PixelMap): PixelMap {
  const result: string[] = [];
  for (const row of map) {
    const doubled = [...row].map((c) => c + c).join("");
    result.push(doubled, doubled);
  }
  return result;
}

function upscaleShape(shape: Record<StageKey, PixelMap>): Record<StageKey, PixelMap> {
  return Object.fromEntries(Object.entries(shape).map(([k, v]) => [k, grounded(upscale2x(v))])) as Record<
    StageKey,
    PixelMap
  >;
}

const SOIL_32 = [
  "........mmmmmmmmmmmmmmmm........",
  "........mmmmmmmmmmmmmmmm........",
  "....mmmmMMMMMMMMMMMMMMMMmmmm....",
  "....mmmmMMMMMMMMMMMMMMMMmmmm....",
  "..mmMMMMMMMMMMMMMMMMMMMMMMMMmm..",
  "..mmMMMMMMMMMMMMMMMMMMMMMMMMmm..",
  "................................",
  "................................",
] as const;

function withSoil32(top: readonly string[]): PixelMap {
  return grounded([...top, ...SOIL_32]);
}

function r32(rows: string[]): string[] {
  return rows.map((r) => r.padEnd(32, "."));
}

function grounded(map: PixelMap): PixelMap {
  const soilStart = map.length - 8;
  let lastStem = -1;
  for (let r = soilStart - 1; r >= 0; r--) {
    if (/[slLfFywm]/i.test(map[r].replace(/\./g, ""))) {
      lastStem = r;
      break;
    }
  }
  if (lastStem < 0 || lastStem >= soilStart - 1) return map;
  const row = map[lastStem];
  const stemOnly = [...row].map((c) => (c === "s" || c === "w" ? c : ".")).join("");
  if (stemOnly.replace(/\./g, "").length === 0) return map;
  const result = [...map];
  for (let r = lastStem + 1; r < soilStart; r++) {
    result[r] = stemOnly;
  }
  return result;
}

// Shared early stages — planted/germination look the same for all shapes
const SHARED_PLANTED: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ff........",
  "................",
]);

const SHARED_GERMINATION: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  ".......ll.......",
  "......ss........",
  "................",
]);

const SHARED_SENESCENCE: PixelMap = withSoil([
  "................",
  "....yy..........",
  "...yyyy....yy...",
  "....yyy...yyyy..",
  ".....yy..yyy....",
  "......yy.yy.....",
  ".......yyy......",
  ".......yy.......",
  "......yy........",
  "......yy........",
  ".......yy.......",
  ".......yy.......",
]);

const SHARED_DORMANT: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ww........",
  "......ww........",
  "......ww........",
  "......ww........",
]);

// ===== BUSH (default — round bushy shape) =====
const BUSH: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "...ll......ll...",
    "..llll....llll..",
    "..lllll..lllll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "......llll......",
    ".....llllll.....",
    "..ll..llll..ll..",
    ".llll..ss..llll.",
    ".lllll.ss.lllll.",
    "..llllsssslll...",
    "....llssssll....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "......llll......",
    "....llllllll....",
    "...llllLlllll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  budding: withSoil([
    "....f.llll.f....",
    "....llllllll....",
    "...lfllLllfll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  flowering: withSoil([
    "...ff.llll.ff...",
    "...fFllllllFf...",
    "..llfllLlllfll..",
    "..lllLllllLlll..",
    ".lfFllllllllFfl.",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  fruiting: withSoil([
    "......llll......",
    "....llllllll....",
    "...lllLllllll...",
    "..lfflllllffll..",
    "..lffLllllffFl..",
    ".lllLllssllLlll.",
    ".llffLssssffll..",
    "..lfFlssssfFll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  harvest: withSoil([
    "....ffllllff....",
    "...fFFllllFFf...",
    "..lffllLlllffl..",
    "..lllLllllLlll..",
    ".lffllllllllffl.",
    ".lfFLllssllLfFl.",
    ".lllllsssslllll.",
    "..lffLssssLffl..",
    "...lfFlsslfFl...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== ROOT (root crop — yield at soil line) =====
const ROOT: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "................",
  ]),
  budding: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  harvest: withSoil([
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    "......ffff......",
    ".....ffffff.....",
    ".....ffFFff.....",
    "......ffff......",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== VINE (trailing, wider than tall) =====
const VINE: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.........",
    "....llll........",
    ".....lsss.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "..ll............",
    ".llll...ll......",
    "..llssllll......",
    "....ssslll......",
    ".....sss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    ".f..........f...",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".ff........ff...",
    ".fF..ll....Ff...",
    "..ll.llll.ll....",
    ".llll..lllllff..",
    ".lLll..llLlFfl..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "..ff..ll..ff....",
    "..Ff.llll.Ff....",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllffLll...",
    "...sssslfFll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "..ff........ff..",
    "..FF..ll..ffFF..",
    "..ff.llll.Ffff..",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllfFLll...",
    "...sssslffll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== TALL (narrow upright — corn, sunflower) =====
const TALL: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  vegetative: withSoil([
    "................",
    "......ll........",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  budding: withSoil([
    ".......f........",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  flowering: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  fruiting: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "....fflsl.......",
    "....Fflsff......",
    ".......sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  harvest: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "....fflsll......",
    "....Ffls.ff.....",
    "......lsl.F.....",
    ".....flslff.....",
    "....FF.sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".......y........",
    ".......y........",
    ".......y........",
    ".......y........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== LEAFY (low rosette — lettuce, spinach) =====
const LEAFY: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....ll..ll......",
    "...llllllll.....",
    "....llllll......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......ff........",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....fff........",
    "....fFffFf......",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llfllLllfllll..",
    ".lLllflllflLll..",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    "...ll.ll.ll.....",
    "..llllllllll....",
    ".lllllLllllll...",
    ".lLllllllllLll..",
    "..llllLlLllll...",
    "...lllllllll....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...yy..yy.yy....",
    "..yyyy.yyyyy....",
    "...yyyyyyyyyy...",
    "....yyyyyyyy....",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== HERB (small, delicate) =====
const HERB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.ll......",
    "......lll.......",
    "......ssl.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......f.........",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....ff.f.......",
    "....fFf.Ff......",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llfl.......",
    "....llfllf......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...lll.llll.....",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== FLOWER (bloom-dominant) =====
const FLOWER: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll.ll.....",
    ".....lllllll....",
    "......llll......",
    "......ssll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "......ff........",
    ".....f..f.......",
    "......ff........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    ".....ffff.......",
    "....fffffF......",
    "...ffFffFff.....",
    "....fffffF......",
    ".....ffff.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== BULB (onion, garlic — bulb at soil line) =====
const BULB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ffs.......",
    ".....ffff.......",
    "......ff........",
  ]),
  fruiting: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    "......ffs.......",
    ".....fffff......",
    ".....ffFff......",
    "......fff.......",
  ]),
  harvest: withSoil([
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    ".....ffff.......",
    "....ffffff......",
    "....fffFff......",
    ".....fffff......",
    "......fff.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== CLIMBING (vertical with trellis lines) =====
const CLIMBING: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wsl.......",
    "......ws........",
  ]),
  seedling: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wsl.......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  vegetative: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wsl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  budding: withSoil([
    "......ww........",
    "......wwf.......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wslf......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  flowering: withSoil([
    "......wwff......",
    "......wwfF......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wslfF.....",
    "......wslff.....",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  fruiting: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......wsl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  harvest: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......wsl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......ws........",
    "......ws........",
  ]),
  senescence: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
  dormant: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
};

// ===== GRASS (grass/grain — many thin blades) =====
const GRASS: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....l.l.l......",
    ".....l.l.l......",
    ".....s.s.s......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....s.s.s.s.....",
    "....s.s.s.s.....",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  budding: withSoil([
    "................",
    "................",
    "...f.f.f.f.f....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  flowering: withSoil([
    "................",
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF...",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  fruiting: withSoil([
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF...",
    "..ff.ff.ff.ff...",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  harvest: withSoil([
    "..ff.ff.ff.ff...",
    "..FF.FF.FF.FF...",
    "..ff.ff.ff.ff...",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== COB (corn — tall stalk with tassel and ear) =====
const COB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......l.........",
    ".....lls........",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    ".......y........",
    "......yy........",
    "......ll........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  fruiting: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    "......lsfff.....",
    ".....llsffF.....",
    "......lsfff.....",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  harvest: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    ".....llsffff....",
    "......lsffFf....",
    ".....llsfffF....",
    "......lsffff....",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== HEAD (cabbage — round ball of leaves with tight inner head) =====
const HEAD: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".......s........",
    "................",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllll......",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    ".....l...l......",
    "....ll..ll......",
    "...llllllll.....",
    "....llllll......",
    "...lllllll......",
    "....lllll.......",
    ".....lll........",
    "......s.........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "....l.....l.....",
    "...ll....ll.....",
    "..llllllllll....",
    "..lllLLLLlll....",
    "..llLLLLLLll....",
    "..lllLLLLlll....",
    "...llllllll.....",
    ".....llll.......",
    "......ss........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "...l.......l....",
    "..ll......ll....",
    "..llllllllll....",
    "..lllfffflll....",
    ".lllffFfFflll...",
    "..lllfffflll....",
    "..llllllllll....",
    "...llllllll.....",
    "....llllll......",
    "......ss........",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "..l.........l...",
    "..ll.......ll...",
    "..llllllllllll..",
    "..lllffffffll...",
    ".lllfFfffFflll..",
    "..lllffffffll...",
    "..llllllllllll..",
    "...llllllllll...",
    "....llllllll....",
    "......ss........",
    "................",
  ]),
  harvest: withSoil([
    ".l...........l..",
    ".ll.........ll..",
    "..llllllllllll..",
    "..llffffffffll..",
    ".lllfFffffFflll.",
    ".lllffFffFfflll.",
    ".lllfFffffFflll.",
    "..llffffffffll..",
    "..llllllllllll..",
    "...llllllllll...",
    "......ss........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== GOURD (melon/pumpkin — vine with big round fruit on the ground) =====
const GOURD: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "........l.......",
    ".......ls.......",
    "........s.......",
    "........s.......",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lls.......",
    ".....llls.......",
    "........s.......",
    "........s.......",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..lllll.........",
    "...lllls........",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..llfll.........",
    "...lllll........",
    "..lllllls.......",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..llfll.........",
    "..llflll........",
    "...lflll........",
    "..lllllls.......",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "...l............",
    "..lll...........",
    "...llll.........",
    "....llls........",
    "......lls.......",
    ".....ffff.......",
    "....fFffFf......",
    "....ffffffs.....",
    ".....ffff.......",
    "........s.......",
    "................",
  ]),
  harvest: withSoil([
    "................",
    "..l.............",
    "..lll...........",
    "...llll.........",
    "....llls........",
    "......lls.......",
    "....fffff.......",
    "...fFffffFf.....",
    "...fFffffffs....",
    "...fFffffFf.....",
    "....fffff.......",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== CROWN (broccoli/cauliflower — stalk with dome floret head) =====
const CROWN: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lls.......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllsl......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllll......",
    "....lllllll.....",
    ".....lllsl......",
    "......lsll......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......fff.......",
    ".....fffff......",
    "......fff.......",
    "....llllll......",
    "...lllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    ".....fffff......",
    "....fFfffFf.....",
    ".....fffff......",
    "....llfflll.....",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  fruiting: withSoil([
    ".....fffff......",
    "....fFfffFf.....",
    "...fffFfFfff....",
    "....fFfffFf.....",
    ".....fffff......",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  harvest: withSoil([
    "....fffffff.....",
    "...fFfFffFff....",
    "..fffFfFfFfff...",
    "...fFfFffFff....",
    "....fffffff.....",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== BERRY (strawberry/blueberry — low bush with dangling fruit) =====
const BERRY: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......lll.......",
    ".....lllll......",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    ".....llll.......",
    "....lllLll......",
    "...llLllLll.....",
    "....lllLll......",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "................",
    ".....llll.......",
    "....lllLll......",
    "...llLllLll.....",
    "....lllLlll.....",
    "....lflLfll.....",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "................",
    "....lllll.......",
    "...lllLlll......",
    "..lllLllLlll....",
    "...llLllLll.....",
    "...lflLlfll.....",
    "....lfffl.......",
    ".....llll.......",
    "......lsl.......",
    "......ss........",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "....lllll.......",
    "...lllLlll......",
    "..lllLllLlll....",
    "...llLllLll.....",
    "....lllLlll.....",
    "...ff.ff.ff.....",
    "....f.fF.f......",
    ".....ff.ff......",
    "......ss........",
    "................",
  ]),
  harvest: withSoil([
    "................",
    "...llllll.......",
    "..lllLlllll.....",
    "..llLlllLlll....",
    "...llLllLll.....",
    "....lllLlll.....",
    "..fff.fff.ff....",
    "..fFf.fFf.fF....",
    "...ff..ff..f....",
    "....ff.fff......",
    "......ss........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== Hand-crafted 32×32 stages =====

// --- BUSH 32×32 (full detail for all growth stages) ---
const BUSH_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  ".............llll",
  "..............ls",
  "..............ss",
  "..............ss",
  "..............ss",
]));

const BUSH_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll..ll",
  "...........lllllll",
  "............llll",
  ".............lsl",
  "............llsl",
  ".............lsl",
  ".............ss",
  ".............ss",
  ".............ss",
  ".............ss",
  ".............ss",
]));

const BUSH_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........llllllll",
  "........llllllllllll",
  ".......lllllLllllllll",
  "......llllLllllllLllll",
  "......llllllllllllllll",
  ".......lllLlllllLlllll",
  "......lllllllllllllllll",
  ".......llllllllllllllll",
  "........lllLlllllLlll",
  ".........llllllllllll",
  "..........llllllllll",
  "...........llllllll",
  "...........llllllll",
  "............llllll",
  "............llllll",
  ".............llll",
  ".............llll",
]));

const BUSH_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "..........fllllllllf",
  ".........llllllllllll",
  "........llfllLllllfll",
  ".......lllLllllllllLll",
  "......llllllfllllllflll",
  "......lllLllllllllllLll",
  ".......lllllllllllllll",
  "......lllLllllllllLllll",
  ".......lllllllllllllll",
  "........llllllllllllll",
  ".........lllLlllLllll",
  "..........llllllllll",
  "...........llllllll",
  "...........llllllll",
  "............llllll",
  "............llllll",
  ".............llll",
  ".............llll",
]));

const BUSH_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  ".........fflllllllff",
  "........fFllllllllllFf",
  "........lllllllllllll",
  ".......llfFlLllllfFll",
  "......lllLllllllllLlll",
  ".....lfFllllllllllllFfl",
  ".....llllLlllllllllLlll",
  "......fFllllllllllllfFl",
  "......lllLllllllllLllll",
  ".......llllllllllllllll",
  "........lllLlllLllllll",
  ".........llllllllllll",
  "..........llllllllll",
  "...........llllllll",
  "...........llllllll",
  "............llllll",
  "............llllll",
  ".............llll",
  ".............llll",
]));

const BUSH_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "..........lllllllll",
  "........llllllLllllll",
  ".......lllllllllllllll",
  "......lllfflLllllfflll",
  "......llfFFlllllllfFFll",
  ".....llllfFlllllllfFllll",
  ".....llllllLlllllLllllll",
  "......lllllllllllllllll",
  "......lllLlllllllllLlll",
  ".......llfflllllllffll",
  "........llfFlLllfFll",
  ".........llllllllllll",
  "..........llllllllll",
  "...........llllllll",
  "...........llllllll",
  "............llllll",
  "............llllll",
  ".............llll",
  ".............llll",
]));

const BUSH_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  ".........lllllllllll",
  "........lllllLlllllll",
  ".......lllLlllllllLllll",
  "......llfFFllllllfFFllll",
  ".....lllfFFFlLlllfFFFllll",
  ".....llllfFFlllllllfFFlll",
  "......llllllLlllllLlllll",
  "......lllllllllllllllllll",
  ".......llllLlllllLllllll",
  "......llllllllllllllllll",
  "......llfFFllllllllfFFll",
  ".....lllfFFFlLlllfFFFllll",
  "......llllfFlllllllfFllll",
  ".......llllllLlllLllllll",
  "........llllllllllllll",
  ".........lllllllllllll",
  "..........llllllllll",
  "...........llllllll",
  "............llllll",
  ".............llll",
]));

// --- ROOT 32×32 (full detail — foliage above, root swells below soil) ---
const ROOT_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  ".............llll",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
]));

const ROOT_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "........llllssllll",
  "..........llssll",
  ".............ssss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
]));

const ROOT_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "......l..ll....ll..l",
  ".....lll.llll.llll.lll",
  "......lllllllllllllll",
  ".....lllllLlllLlllllll",
  "......llllllllllllllll",
  ".......lllllssllllll",
  "........lllssssllll",
  "..........llssssll",
  "...........lsssssl",
  "............sssss",
  "............sFFss",
  "............sFFss",
  ".............Fff",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  ".....l..ll....ll..l..",
  "....lll.llll.llll.lll",
  ".....lllllllllllllllll",
  "....lllllLlllLlllLllll",
  ".....llllllllllllllllll",
  "......lllllllllllllll",
  ".......llllssssllllll",
  "........lllssssslll",
  "..........llsssssll",
  "...........lsssssl",
  "...........sssssss",
  "...........sFFFFFs",
  "...........sFFFFFs",
  "...........fFFFFFf",
  "............fFFFf",
  "",
  "",
  "",
  "",
]));

const ROOT_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  ".....l..ll....ll..l..",
  "....lll.llll.llll.lll",
  ".....lllllllllllllllll",
  "....lllllLlllLlllLllll",
  ".....lllllllllllllllllll",
  "......llllllllllllllll",
  ".......lllllllllllll",
  "........lllssssslll",
  "..........llsssssll",
  "...........lsssssl",
  "...........sssssss",
  "...........sFFFFFs",
  "..........fFFFFFFFf",
  "..........fFFFFFFFf",
  "..........fFfFFFfFf",
  "...........fFFFFFf",
  "............fFFFf",
  "",
  "",
  "",
]));

const ROOT_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  ".....l..ll....ll..l..",
  "....lll.llll.llll.lll",
  ".....lllllllllllllllll",
  "....lllllLlllLlllLllll",
  ".....lllllllllllllllllll",
  "......llllllllllllllllll",
  ".......lllllllllllllll",
  "........lllssssslll",
  "..........llsssssll",
  "...........lsssssl",
  "...........sssssss",
  "..........sFFFFFFFs",
  ".........fFFFFFFFFFf",
  ".........fFFFFFFFFFf",
  ".........fFfFFFFFfFf",
  ".........fFFfFFFfFFf",
  "..........fFFFFFFFf",
  "...........fFFFFFf",
  "............fFFFf",
  "",
  "",
]));

const ROOT_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  ".....l..ll....ll..l..",
  "....lll.llll.llll.lll",
  ".....lllllllllllllllll",
  "....lllllLlllLlllLllll",
  ".....lllllllllllllllllll",
  "......llllllllllllllllll",
  ".......llllllllllllllll",
  "........lllllllllllll",
  ".........lllssssslll",
  "..........llsssssll",
  "...........lsssssl",
  "...........sssssss",
  "..........sFFFFFFFs",
  ".........fFFFFFFFFFf",
  "........fFFFFFFFFFFFf",
  "........fFFFFFFFFFFFf",
  "........fFfFFFFFFFfFf",
  "........fFFfFFFFFfFFf",
  ".........fFFFFFFFFFf",
  "..........fFFFFFFFf",
  "...........fFFFFFf",
  "............fFFFf",
]));

// --- VINE 32×32 hand-crafted (3/10) ---

const VINE_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  ".............llll",
  ".............lLl",
  "..............s",
  "..............s",
]));

const VINE_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "...........ll",
  "..........llll....ll",
  "..........lLll...llll",
  "...........lsl...lLl",
  ".........llssll...l",
  "........llllll",
  ".........lLll",
  "..........s",
]));

const VINE_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......ll",
  "......llll........ll",
  "....ll.lLll......llll",
  "....llllsls.....lLlll",
  "....lLlsssssll...lLl",
  "...lllllssssllll..l",
  "....lLll.ssllLlll",
  "...l.ll...lllLll",
  "..............l",
]));

const VINE_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......ll.......f",
  "......llll.....ff",
  "....ll.lLll.......ll",
  "....llllsls.....llll",
  "..ll.lLlsssssll.lLlll",
  ".llll.lllssssllll.lLl",
  ".lLll....ssllLlllllll",
  "..ll.l...sllllLlll.l",
  "f........s.lllLll",
  "ff.......s..ll.l",
  ".........s",
]));

const VINE_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......ll.......f",
  "......llll.....ff",
  "....ll.lLll.......ll",
  "....llllsls.....llll",
  "..ll.lLlsssssll.lLlll",
  "f.llll.lllssssllll.lLl",
  "ff.lLll....ssllLlllllff",
  "..ll.l...sllllLlllllFf",
  "f........s.lllLlll..f",
  "Ff.......s..llll",
  ".f.......s",
  "",
  "",
]));

const VINE_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......ll.......f",
  "......llll.....FF",
  "....ll.lLll.....Ff..ll",
  "....llllsls....fffllll",
  "..ll.lLlsssssll.flLlll",
  "f.llll.lllssssllllllLl",
  "ffflLll....ssllLllllffl",
  "ffll.l...sllllLlllllFff",
  "fF.......s.lllLlllllff",
  "Ff.......s..llllll",
  ".f.......s....ll",
  "",
  "",
  "",
  "",
  "",
]));

const VINE_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......ll........FF",
  "......llll......FFF",
  "....ll.lLll.....fFf.ll",
  "..ffllllsls....fFfllll",
  ".fFflLlsssssll.flLlll",
  "fFFflll.lllssssllllllLl",
  "fFfllLll....ssllLllllffl",
  ".fll.l...sllllLlllllFFf",
  "fF.......s.lllLlllllFFf",
  "FFf......s..lllllll.fF",
  ".f.......s....llll",
  "",
  "",
  "",
  "",
  "",
  "",
]));

// --- GRASS 32×32 hand-crafted (10/10) ---

const GRASS_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".........l.l.l",
  ".........l.l.l",
  ".........s.s.s",
  ".........s.s.s",
]));

const GRASS_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "........l.l.l.l",
  "........l.l.l.l",
  "........l.l.l.l",
  "........l.l.l.l",
  "........s.s.s.s",
  "........s.s.s.s",
  "",
  "",
]));

const GRASS_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  "",
  "",
]));

const GRASS_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".......f.f.f.f.f",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  "",
  "",
]));

const GRASS_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "......ff.ff.ff.ff",
  "......fF.fF.fF.fF",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  "",
  "",
]));

const GRASS_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "......ff.ff.ff.ff",
  "......fF.fF.fF.fF",
  "......ff.ff.ff.ff",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......l.l.l.l.l",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  "",
  "",
]));

const GRASS_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "......ff.ff.ff.ff",
  "......FF.FF.FF.FF",
  "......ff.ff.ff.ff",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......y.y.y.y.y",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  ".......s.s.s.s.s",
  "",
  "",
]));

// --- CLIMBING 32×32 hand-crafted (9/10) ---

const CLIMBING_32_SPROUT: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "..........ws",
]));

const CLIMBING_32_SEEDLING: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwl",
  "..........wlll",
  "..........wsl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "..........ws",
  "",
  "",
]));

const CLIMBING_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwl",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........wsl",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........wsl",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "",
  "",
]));

const CLIMBING_32_BUDDING: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwf",
  "..........wwl",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........wslf",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........wsl",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "..........ws",
  "..........ws",
  "",
  "",
]));

const CLIMBING_32_FLOWERING: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwff",
  "..........wwfF",
  "..........wwl",
  "..........wlll",
  "..........wlLl",
  "..........wslfF",
  "..........wslff",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........wslfF",
  "..........wlll",
  "..........wlLl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "..........ws",
  "..........ws",
  "",
  "",
]));

const CLIMBING_32_FRUITING: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwl",
  "..........wlfl",
  "..........wlfFl",
  "..........wsl",
  "..........wsl",
  "..........wlfl",
  "..........wlfFl",
  "..........wsl",
  "..........wsl",
  "..........wlfl",
  "..........wlfFl",
  "..........wsl",
  "..........ws",
  "..........ws",
  "..........ws",
  "..........ws",
  "",
  "",
]));

const CLIMBING_32_HARVEST: PixelMap = withSoil32(r32([
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........ww",
  "..........wwl",
  "..........wlffl",
  "..........wlfFl",
  "..........wslfF",
  "..........wsl",
  "..........wlffl",
  "..........wlfFl",
  "..........wslfF",
  "..........wsl",
  "..........wlffl",
  "..........wlfFl",
  "..........wslfF",
  "..........ws",
  "..........ws",
  "..........ws",
  "..........ws",
  "",
  "",
]));

// --- BULB 32×32 hand-crafted (8/10) ---

const BULB_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  ".............l",
  "............ss",
  "............ss",
  "",
  "",
]));

const BULB_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  ".............s",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const BULB_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  "............lll",
  ".............l",
  "............ll",
  ".............l",
  ".............s",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const BULB_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  "............lll",
  ".............l",
  "............ll",
  ".............l",
  ".............s",
  "............ss",
  "............ss",
  "............ff",
  "............ff",
]));

const BULB_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  "............lll",
  ".............l",
  "............ll",
  ".............l",
  ".............s",
  "............ss",
  "...........ffs",
  "..........fffff",
  "...........fff",
  "............ss",
]));

const BULB_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  "............lll",
  ".............l",
  "............ll",
  ".............s",
  "............ss",
  "..........fffs",
  ".........ffffff",
  ".........fffFff",
  "..........ffff",
  "...........ss",
  "...........ss",
]));

const BULB_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".............l",
  "............ll",
  ".............l",
  "............lll",
  ".............l",
  "............ll",
  ".............s",
  "............ss",
  "........fffff",
  ".......ffffffff",
  ".......ffffFfff",
  "........ffffff",
  ".........ffff",
  "..........ss",
  "..........ss",
]));

// --- FLOWER 32×32 hand-crafted (7/10) ---

const FLOWER_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "...........ll",
  "..........llll",
  "...........ss",
  "...........ss",
  "...........ss",
  "...........ss",
  "",
  "",
]));

const FLOWER_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ll.ll",
  ".........lllllll",
  "..........llll",
  "..........ssll",
  "...........ss",
  "...........ss",
  "...........ss",
  "",
  "",
  "",
  "",
]));

const FLOWER_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ll",
  ".........llll",
  "........llllll",
  ".......ll.ssl.ll",
  "........llssll",
  ".........ssss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const FLOWER_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ff",
  ".........f..f",
  "..........ff",
  ".........llll",
  "........llllll",
  ".......ll.ssl.ll",
  "........llssll",
  ".........ssss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const FLOWER_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  ".........fffff",
  "........fffffFf",
  ".......ffFffFfff",
  "........fffffFf",
  ".........fffff",
  "........llllll",
  ".......ll.ssl.ll",
  "........llssll",
  ".........ssss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const FLOWER_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "........fffffff",
  ".......fFfffffFf",
  "......fffFffFffff",
  "......ffFfffffFff",
  ".......ffffffFff",
  "........llllll",
  ".......ll.ssl.ll",
  "........llssll",
  ".........ssss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const FLOWER_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "........fffffff",
  ".......fFfffffFf",
  "......fffFffFffff",
  "......ffFfffffFff",
  ".......ffffffFff",
  "........llllll",
  ".......ll.ssl.ll",
  "........llssll",
  ".........ssss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

// --- HERB 32×32 hand-crafted (6/10) ---

const HERB_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  "...............l",
  "..............ss",
  "..............ss",
  "",
  "",
]));

const HERB_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "...........ll.ll",
  "............lll",
  "............ssl",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const HERB_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "..........ll.lll",
  ".........ll.ssl.ll",
  "..........llssll",
  "...........ssss",
  "............ss",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const HERB_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............f",
  "............ll",
  "...........llll",
  "..........ll.lll",
  ".........ll.ssl.ll",
  "..........llssll",
  "...........ssss",
  "............ss",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const HERB_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "...........ff.f",
  "..........fFf.Ff",
  "............ll",
  "...........llll",
  "..........ll.lll",
  ".........ll.ssl.ll",
  "..........llssll",
  "...........ssss",
  "............ss",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const HERB_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llfl",
  "..........llflll",
  ".........ll.ssl.ll",
  "..........llssll",
  "...........ssss",
  "............ss",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const HERB_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "..........llllll",
  ".........lll.llll",
  ".........ll.ssl.ll",
  "..........llssll",
  "...........ssss",
  "............ss",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

// --- LEAFY 32×32 hand-crafted (5/10) ---

const LEAFY_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  ".............llll",
  "..............ss",
  "..............ss",
  "",
  "",
]));

const LEAFY_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ll..ll",
  ".........llllllll",
  "..........llllll",
  "............ss",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
]));

const LEAFY_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "......ll...llll..ll",
  ".....llll.llLlllllll",
  ".....lLllllllllllLll",
  "......lllllLllllll",
  ".......llllllllll",
  "........llssllll",
  "..........ssll",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const LEAFY_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ff",
  "............ll",
  "......ll...llll..ll",
  ".....llll.llLlllllll",
  ".....lLllllllllllLll",
  "......lllllLllllll",
  ".......llllllllll",
  "........llssllll",
  "..........ssll",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const LEAFY_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".........fff",
  "........fFffFf",
  "..........ffll",
  "......ll...llll..ll",
  ".....llll.llLlllllll",
  ".....lLllllllllllLll",
  "......lllllLllllll",
  ".......llllllllll",
  "........llssllll",
  "..........ssll",
  "..........ss",
  "..........ss",
  "",
  "",
  "",
  "",
]));

const LEAFY_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "......ll...llll..ll",
  ".....llll.lllllllll",
  ".....lLllllllllllLll",
  "......llllllllllll",
  ".......lllllllllll",
  "........llllllllll",
  "..........lllllll",
  "...........lllll",
  "............lll",
  ".............ss",
  ".............ss",
  ".............ss",
  ".............ss",
]));

const LEAFY_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ll",
  "........ll.ll..ll",
  "......llll.llll.llll",
  ".....lllllllLllllllll",
  ".....lLlllllllllllLll",
  "......llllllLllllllll",
  "......lllllLlLllllll",
  ".......lllllllllllll",
  "........llllllllll",
  "..........lllllll",
  "............lll",
  ".............ss",
  ".............ss",
  ".............ss",
  ".............ss",
]));

// --- TALL 32×32 hand-crafted (4/10) ---

const TALL_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............l",
  ".............ll",
  "..............sl",
  "..............s",
  "..............s",
  "..............s",
]));

const TALL_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "............lsl",
  ".............sl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
]));

const TALL_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  ".............ff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "........fflsll",
  "........Fflsl",
  "...........lsff",
  "..........llslFf",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "........fflslll",
  "........FFlsl",
  "........fflsll",
  "........Fflsl",
  "...........lsff",
  "..........llslFF",
  "...........lslff",
  ".............sFF",
  "..............sf",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

// --- COB, HEAD, GOURD, CROWN, BERRY overrides (fruiting + harvest) ---

const COB_32_FRUITING: PixelMap = withSoil32(r32([
  "............yyyyy",
  "...........yyyyyy",
  "............yyyy",
  "...........llyl",
  "..........lllsl",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  "..........llslfffff",
  ".........lllslffFfff",
  "..........llslfffffFf",
  ".........lllslffFfff",
  "..........llslfffff",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  "..........lls",
  "............ls",
  ".............s",
  ".............s",
  ".............s",
  ".............s",
  "",
  "",
]));

const COB_32_HARVEST: PixelMap = withSoil32(r32([
  "............yyyyy",
  "...........yyyyyy",
  "............yyyy",
  "...........llyyl",
  "..........lllsl",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  ".........lllslffffffl",
  "..........llslffFfFffl",
  ".........lllslfffffFfFf",
  "..........llslffFffFffl",
  ".........lllslfffffFfFf",
  "..........llslffFfFffl",
  ".........lllslffffffl",
  "..........llsl",
  ".........lllsl",
  "..........lls",
  "............ls",
  ".............s",
  ".............s",
  ".............s",
  ".............s",
  "",
]));

const HEAD_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "....l...............l",
  "...ll..............ll",
  "...lllll......lllll",
  "...llllllllllllllll",
  "..lllllllllllllllll",
  "..lllllffffffffllll",
  "..llllffFffffffflll",
  ".lllllffFfffFfffllll",
  ".lllllfffffffffflll",
  "..llllffFfffFffflll",
  "..lllllffffffffllll",
  "..lllllllllllllllll",
  "...llllllllllllllll",
  "....llllllllllllll",
  ".....lllllllllll",
  "......llllllllll",
  "........llll",
  ".........ss",
  ".........ss",
  "",
  "",
  "",
]));

const HEAD_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "..l.................l",
  "..ll...............ll",
  "..lllll.......lllll",
  "..lllllllllllllllllll",
  "..llllllllllllllllllll",
  ".llllllfffffffffflllll",
  ".lllllffFfffFfFffflll",
  ".llllffFfFfffffFFfflll",
  ".llllfffffffFfffffllll",
  ".llllffFfffFfFfFffflll",
  ".llllfffFfffffFfFfflll",
  ".lllllffFfffFfFffflll",
  ".llllllfffffffffflllll",
  "..llllllllllllllllllll",
  "..lllllllllllllllllll",
  "...lllllllllllllllll",
  "....llllllllllllll",
  ".....lllllllllll",
  ".........ssss",
  ".........ss",
  "",
  "",
  "",
]));

const GOURD_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "......l",
  ".....lll",
  "....lllll",
  ".....lllll",
  "......lllls",
  ".......lllls",
  ".........llls",
  "...........lls",
  "..........fffff",
  ".........fFfffFf",
  "........fFffffffFf",
  "........ffffffffff",
  "........fFffffffFf",
  ".........fFfffFf",
  "..........fffff",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
]));

const GOURD_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "....l",
  "....lll",
  ".....llll",
  "......lllls",
  ".......lllls",
  "..........llls",
  "............lls",
  ".........fffffff",
  "........fFfffffFf",
  ".......fFfffffffffFf",
  "......fFfffFfffFfffFf",
  "......ffffffFffffffFf",
  "......fFfffFfffFfffFfs",
  ".......fFfffffffffFf",
  "........fFfffffFf",
  ".........fffffff",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
]));

const CROWN_32_FRUITING: PixelMap = withSoil32(r32([
  ".........fffffffffff",
  "........fFfffFfffFff",
  ".......fffFfFfFfFffff",
  "......fffffFfFfFfffff",
  ".......fffFfFfFfFffff",
  "........fFfffFfffFff",
  ".........fffffffffff",
  ".......llllllllllll",
  "......lllllllllllllll",
  ".....llllllllllllllll",
  "......lllllllllllllll",
  ".......llllllllllsl",
  "........lllllllslll",
  ".........llllslll",
  "..........llsll",
  "...........lsl",
  "............ls",
  ".............s",
  ".............s",
  "",
  "",
  "",
  "",
  "",
]));

const CROWN_32_HARVEST: PixelMap = withSoil32(r32([
  "........fffffffffffff",
  ".......fFfFffFfFffFff",
  "......ffffFfFfFfFffffff",
  ".....fFfFffFffFffFfFfff",
  ".....fffffFfFfFfFfFffff",
  "......fFfFffFffFffFfFf",
  ".......ffffFfFfFfffff",
  "........fffffffffffff",
  ".......llllllllllllll",
  "......llllllllllllllll",
  ".....lllllllllllllllll",
  "......llllllllllllllll",
  ".......llllllllllsl",
  "........llllllslll",
  ".........lllslll",
  "..........llsll",
  "...........lsl",
  "............ls",
  ".............s",
  "",
  "",
  "",
  "",
  "",
]));

const BERRY_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "........llllllll",
  ".......llllLllll",
  "......lllLllllLlll",
  ".....llllLllllLllll",
  "......lllLllllLllll",
  ".......llllLlllll",
  "........llllllllll",
  "......ff..fff..ff",
  ".......ff..fF..ff",
  "........f...f...f",
  "..........ff..ff",
  "...........ff",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BERRY_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  ".......lllllllll",
  "......llllLllllll",
  ".....lllLllllLllll",
  "....llllLllllLlllll",
  ".....lllLllllLlllll",
  "......llllLlllllll",
  ".....fff.ffff.fff",
  "....fFff.fFfF.fFff",
  "....fff..ffff..fff",
  ".....ff.fffff.fff",
  "......ff.fFfF.ff",
  ".......ff.fff.f",
  "........ff..ff",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

/** All shape families keyed by SpriteShape, at 32×32 resolution. */
export const SHAPE_MAPS: Record<SpriteShape, Record<StageKey, PixelMap>> = {
  bush: {
    ...upscaleShape(BUSH),
    sprout: BUSH_32_SPROUT,
    seedling: BUSH_32_SEEDLING,
    vegetative: BUSH_32_VEGETATIVE,
    budding: BUSH_32_BUDDING,
    flowering: BUSH_32_FLOWERING,
    fruiting: BUSH_32_FRUITING,
    harvest: BUSH_32_HARVEST,
  },
  root: {
    ...upscaleShape(ROOT),
    sprout: ROOT_32_SPROUT,
    seedling: ROOT_32_SEEDLING,
    vegetative: ROOT_32_VEGETATIVE,
    budding: ROOT_32_BUDDING,
    flowering: ROOT_32_FLOWERING,
    fruiting: ROOT_32_FRUITING,
    harvest: ROOT_32_HARVEST,
  },
  vine: {
    ...upscaleShape(VINE),
    sprout: VINE_32_SPROUT,
    seedling: VINE_32_SEEDLING,
    vegetative: VINE_32_VEGETATIVE,
    budding: VINE_32_BUDDING,
    flowering: VINE_32_FLOWERING,
    fruiting: VINE_32_FRUITING,
    harvest: VINE_32_HARVEST,
  },
  tall: {
    ...upscaleShape(TALL),
    sprout: TALL_32_SPROUT,
    seedling: TALL_32_SEEDLING,
    vegetative: TALL_32_VEGETATIVE,
    budding: TALL_32_BUDDING,
    flowering: TALL_32_FLOWERING,
    fruiting: TALL_32_FRUITING,
    harvest: TALL_32_HARVEST,
  },
  leafy: {
    ...upscaleShape(LEAFY),
    sprout: LEAFY_32_SPROUT,
    seedling: LEAFY_32_SEEDLING,
    vegetative: LEAFY_32_VEGETATIVE,
    budding: LEAFY_32_BUDDING,
    flowering: LEAFY_32_FLOWERING,
    fruiting: LEAFY_32_FRUITING,
    harvest: LEAFY_32_HARVEST,
  },
  herb: {
    ...upscaleShape(HERB),
    sprout: HERB_32_SPROUT,
    seedling: HERB_32_SEEDLING,
    vegetative: HERB_32_VEGETATIVE,
    budding: HERB_32_BUDDING,
    flowering: HERB_32_FLOWERING,
    fruiting: HERB_32_FRUITING,
    harvest: HERB_32_HARVEST,
  },
  flower: {
    ...upscaleShape(FLOWER),
    sprout: FLOWER_32_SPROUT,
    seedling: FLOWER_32_SEEDLING,
    vegetative: FLOWER_32_VEGETATIVE,
    budding: FLOWER_32_BUDDING,
    flowering: FLOWER_32_FLOWERING,
    fruiting: FLOWER_32_FRUITING,
    harvest: FLOWER_32_HARVEST,
  },
  bulb: {
    ...upscaleShape(BULB),
    sprout: BULB_32_SPROUT,
    seedling: BULB_32_SEEDLING,
    vegetative: BULB_32_VEGETATIVE,
    budding: BULB_32_BUDDING,
    flowering: BULB_32_FLOWERING,
    fruiting: BULB_32_FRUITING,
    harvest: BULB_32_HARVEST,
  },
  climbing: {
    ...upscaleShape(CLIMBING),
    sprout: CLIMBING_32_SPROUT,
    seedling: CLIMBING_32_SEEDLING,
    vegetative: CLIMBING_32_VEGETATIVE,
    budding: CLIMBING_32_BUDDING,
    flowering: CLIMBING_32_FLOWERING,
    fruiting: CLIMBING_32_FRUITING,
    harvest: CLIMBING_32_HARVEST,
  },
  grass: {
    ...upscaleShape(GRASS),
    sprout: GRASS_32_SPROUT,
    seedling: GRASS_32_SEEDLING,
    vegetative: GRASS_32_VEGETATIVE,
    budding: GRASS_32_BUDDING,
    flowering: GRASS_32_FLOWERING,
    fruiting: GRASS_32_FRUITING,
    harvest: GRASS_32_HARVEST,
  },
  cob: { ...upscaleShape(COB), fruiting: COB_32_FRUITING, harvest: COB_32_HARVEST },
  head: { ...upscaleShape(HEAD), fruiting: HEAD_32_FRUITING, harvest: HEAD_32_HARVEST },
  gourd: { ...upscaleShape(GOURD), fruiting: GOURD_32_FRUITING, harvest: GOURD_32_HARVEST },
  crown: { ...upscaleShape(CROWN), fruiting: CROWN_32_FRUITING, harvest: CROWN_32_HARVEST },
  berry: { ...upscaleShape(BERRY), fruiting: BERRY_32_FRUITING, harvest: BERRY_32_HARVEST },
};

// Keep legacy exports for backwards compatibility
export const STAGE_MAPS = BUSH;
export const ROOT_STAGE_MAPS: Partial<Record<StageKey, PixelMap>> = {
  fruiting: ROOT.fruiting,
  harvest: ROOT.harvest,
};

/** Maps must stay 16×16 and only use palette slots; verified by tests. */
export const PALETTE_SLOTS = new Set([
  ".",
  "m",
  "M",
  "s",
  "l",
  "L",
  "f",
  "F",
  "y",
  "w",
]);
