/**
 * Stage sprite pixel maps (§13.5, §21.4). Multiple shape families so
 * different plant types get distinct silhouettes. Characters are palette
 * slots — a single map renders per-category (and per-plant accent) variants:
 *
 *   .  transparent      s  stem          f  accent (fruit/bloom)
 *   m  soil light       l  leaf          F  accent shade
 *   M  soil dark        L  leaf shade    y  dry/senescent
 *   w  wood/stub
 */

import type { StageKey } from "../types/models";

export type PixelMap = readonly string[];

export type SpriteShape =
  | "bush"
  | "root"
  | "vine"
  | "tall"
  | "leafy"
  | "herb"
  | "flower"
  | "bulb"
  | "climbing"
  | "grass";

export const SHAPE_LABELS: Record<SpriteShape, string> = {
  bush: "Bush",
  root: "Root crop",
  vine: "Vine / Trailing",
  tall: "Tall / Upright",
  leafy: "Leafy / Rosette",
  herb: "Herb",
  flower: "Flower",
  bulb: "Bulb",
  climbing: "Climbing / Trellis",
  grass: "Grass / Grain",
};

const SOIL = [
  "....mmmmmmmm....",
  "..mmMMMMMMMMmm..",
  ".mMMMMMMMMMMMMm.",
  "................",
] as const;

function withSoil(top: readonly string[]): PixelMap {
  return [...top, ...SOIL];
}

// Shared early stages — planted/germination look the same for all shapes
const SHARED_PLANTED: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ff........",
  "................",
]);

const SHARED_GERMINATION: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  ".......ll.......",
  "......ss........",
  "................",
]);

const SHARED_SENESCENCE: PixelMap = withSoil([
  "................",
  "....yy..........",
  "...yyyy....yy...",
  "....yyy...yyyy..",
  ".....yy..yyy....",
  "......yy.yy.....",
  ".......yyy......",
  ".......yy.......",
  "......yy........",
  "......yy........",
  ".......yy.......",
  ".......yy.......",
]);

const SHARED_DORMANT: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ww........",
  "......ww........",
  "......ww........",
  "......ww........",
]);

// ===== BUSH (default — round bushy shape) =====
const BUSH: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "...ll......ll...",
    "..llll....llll..",
    "..lllll..lllll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "......llll......",
    ".....llllll.....",
    "..ll..llll..ll..",
    ".llll..ss..llll.",
    ".lllll.ss.lllll.",
    "..llllsssslll...",
    "....llssssll....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "......llll......",
    "....llllllll....",
    "...llllLlllll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  budding: withSoil([
    "....f.llll.f....",
    "....llllllll....",
    "...lfllLllfll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  flowering: withSoil([
    "...ff.llll.ff...",
    "...fFllllllFf...",
    "..llfllLlllfll..",
    "..lllLllllLlll..",
    ".lfFllllllllFfl.",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  fruiting: withSoil([
    "......llll......",
    "....llllllll....",
    "...lllLllllll...",
    "..lfflllllffll..",
    "..lffLllllffFl..",
    ".lllLllssllLlll.",
    ".llffLssssffll..",
    "..lfFlssssfFll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  harvest: withSoil([
    "....ffllllff....",
    "...fFFllllFFf...",
    "..lffllLlllffl..",
    "..lllLllllLlll..",
    ".lffllllllllffl.",
    ".lfFLllssllLfFl.",
    ".lllllsssslllll.",
    "..lffLssssLffl..",
    "...lfFlsslfFl...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== ROOT (root crop — yield at soil line) =====
const ROOT: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "................",
  ]),
  budding: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  harvest: withSoil([
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    "......ffff......",
    ".....ffffff.....",
    ".....ffFFff.....",
    "......ffff......",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== VINE (trailing, wider than tall) =====
const VINE: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.........",
    "....llll........",
    ".....lsss.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "..ll............",
    ".llll...ll......",
    "..llssllll......",
    "....ssslll......",
    ".....sss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    ".f..........f...",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".ff........ff...",
    ".fF..ll....Ff...",
    "..ll.llll.ll....",
    ".llll..lllllff..",
    ".lLll..llLlFfl..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "..ff..ll..ff....",
    "..Ff.llll.Ff....",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllffLll...",
    "...sssslfFll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "..ff........ff..",
    "..FF..ll..ffFF..",
    "..ff.llll.Ffff..",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllfFLll...",
    "...sssslffll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== TALL (narrow upright — corn, sunflower) =====
const TALL: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  vegetative: withSoil([
    "................",
    "......ll........",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  budding: withSoil([
    ".......f........",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  flowering: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  fruiting: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "....fflsl.......",
    "....Fflsff......",
    ".......sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  harvest: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "....fflsll......",
    "....Ffls.ff.....",
    "......lsl.F.....",
    ".....flslff.....",
    "....FF.sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".......y........",
    ".......y........",
    ".......y........",
    ".......y........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== LEAFY (low rosette — lettuce, spinach) =====
const LEAFY: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....ll..ll......",
    "...llllllll.....",
    "....llllll......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......ff........",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....fff........",
    "....fFffFf......",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llfllLllfllll..",
    ".lLllflllflLll..",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    "...ll.ll.ll.....",
    "..llllllllll....",
    ".lllllLllllll...",
    ".lLllllllllLll..",
    "..llllLlLllll...",
    "...lllllllll....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...yy..yy.yy...",
    "..yyyy.yyyyy....",
    "...yyyyyyyyyy...",
    "....yyyyyyyy....",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== HERB (small, delicate) =====
const HERB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.ll......",
    "......lll.......",
    "......ssl.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......f.........",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....ff.f.......",
    "....fFf.Ff......",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llfl.......",
    "....llfllf......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...lll.llll.....",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== FLOWER (bloom-dominant) =====
const FLOWER: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll.ll.....",
    ".....lllllll....",
    "......llll......",
    "......ssll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "......ff........",
    ".....f..f.......",
    "......ff........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    ".....ffff.......",
    "....fffffF......",
    "...ffFffFff.....",
    "....fffffF......",
    ".....ffff.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== BULB (onion, garlic — bulb at soil line) =====
const BULB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ffs.......",
    ".....ffff.......",
    "......ff........",
  ]),
  fruiting: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    "......ffs.......",
    ".....fffff......",
    ".....ffFff......",
    "......fff.......",
  ]),
  harvest: withSoil([
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    ".....ffff.......",
    "....ffffff......",
    "....fffFff......",
    ".....fffff......",
    "......fff.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== CLIMBING (vertical with trellis lines) =====
const CLIMBING: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wsl.......",
    "......ws........",
  ]),
  seedling: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wsl.......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  vegetative: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wsl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  budding: withSoil([
    "......ww........",
    "......wwf.......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wslf......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  flowering: withSoil([
    "......wwff......",
    "......wwfF......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wslfF.....",
    "......wslff.....",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  fruiting: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......wsl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  harvest: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......wsl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......ws........",
    "......ws........",
  ]),
  senescence: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
  dormant: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
};

// ===== GRASS (grass/grain — many thin blades) =====
const GRASS: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....l.l.l......",
    ".....l.l.l......",
    ".....s.s.s......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....s.s.s.s.....",
    "....s.s.s.s.....",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  budding: withSoil([
    "................",
    "................",
    "...f.f.f.f.f....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  flowering: withSoil([
    "................",
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF..",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  fruiting: withSoil([
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF..",
    "..ff.ff.ff.ff...",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  harvest: withSoil([
    "..ff.ff.ff.ff...",
    "..FF.FF.FF.FF...",
    "..ff.ff.ff.ff...",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
  ]),
  dormant: SHARED_DORMANT,
};

/** All shape families keyed by SpriteShape. */
export const SHAPE_MAPS: Record<SpriteShape, Record<StageKey, PixelMap>> = {
  bush: BUSH,
  root: ROOT,
  vine: VINE,
  tall: TALL,
  leafy: LEAFY,
  herb: HERB,
  flower: FLOWER,
  bulb: BULB,
  climbing: CLIMBING,
  grass: GRASS,
};

// Keep legacy exports for backwards compatibility
export const STAGE_MAPS = BUSH;
export const ROOT_STAGE_MAPS: Partial<Record<StageKey, PixelMap>> = {
  fruiting: ROOT.fruiting,
  harvest: ROOT.harvest,
};

/** Maps must stay 16×16 and only use palette slots; verified by tests. */
export const PALETTE_SLOTS = new Set([
  ".",
  "m",
  "M",
  "s",
  "l",
  "L",
  "f",
  "F",
  "y",
  "w",
]);
