/**
 * Stage sprite pixel maps (§13.5, §21.4). Multiple shape families so
 * different plant types get distinct silhouettes. Characters are palette
 * slots — a single map renders per-category (and per-plant accent) variants:
 *
 *   .  transparent      s  stem          f  accent (fruit/bloom)
 *   m  soil light       l  leaf          F  accent shade
 *   M  soil dark        L  leaf shade    y  dry/senescent
 *   w  wood/stub
 */

import type { StageKey } from "../types/models";

export type PixelMap = readonly string[];

/** Sprite grid resolution — all maps are RES×RES. */
export const SPRITE_RES = 32;

export type SpriteShape =
  | "bush"
  | "root"
  | "vine"
  | "tall"
  | "leafy"
  | "herb"
  | "flower"
  | "bulb"
  | "climbing"
  | "grass"
  | "cob"
  | "head"
  | "gourd"
  | "crown"
  | "berry";

export const SHAPE_LABELS: Record<SpriteShape, string> = {
  bush: "Bush",
  root: "Root crop",
  vine: "Vine / Trailing",
  tall: "Tall / Upright",
  leafy: "Leafy / Rosette",
  herb: "Herb",
  flower: "Flower",
  bulb: "Bulb",
  climbing: "Climbing / Trellis",
  grass: "Grass / Grain",
  cob: "Cob / Ear",
  head: "Head / Ball",
  gourd: "Gourd / Ground fruit",
  crown: "Crown / Floret",
  berry: "Berry bush",
};

const SOIL = [
  "....mmmmmmmm....",
  "..mmMMMMMMMMmm..",
  ".mMMMMMMMMMMMMm.",
  "................",
] as const;

function withSoil(top: readonly string[]): PixelMap {
  return [...top, ...SOIL];
}

function upscale2x(map: PixelMap): PixelMap {
  const result: string[] = [];
  for (const row of map) {
    const doubled = [...row].map((c) => c + c).join("");
    result.push(doubled, doubled);
  }
  return result;
}

function upscaleShape(shape: Record<StageKey, PixelMap>): Record<StageKey, PixelMap> {
  return Object.fromEntries(Object.entries(shape).map(([k, v]) => [k, upscale2x(v)])) as Record<
    StageKey,
    PixelMap
  >;
}

const SOIL_32 = [
  "........mmmmmmmmmmmmmmmm........",
  "........mmmmmmmmmmmmmmmm........",
  "....mmmmMMMMMMMMMMMMMMMMmmmm....",
  "....mmmmMMMMMMMMMMMMMMMMmmmm....",
  "..mmMMMMMMMMMMMMMMMMMMMMMMMMmm..",
  "..mmMMMMMMMMMMMMMMMMMMMMMMMMmm..",
  "................................",
  "................................",
] as const;

function withSoil32(top: readonly string[]): PixelMap {
  return [...top, ...SOIL_32];
}

function r32(rows: string[]): string[] {
  return rows.map((r) => r.padEnd(32, "."));
}

// Shared early stages — planted/germination look the same for all shapes
const SHARED_PLANTED: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ff........",
  "................",
]);

const SHARED_GERMINATION: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  ".......ll.......",
  "......ss........",
  "................",
]);

const SHARED_SENESCENCE: PixelMap = withSoil([
  "................",
  "....yy..........",
  "...yyyy....yy...",
  "....yyy...yyyy..",
  ".....yy..yyy....",
  "......yy.yy.....",
  ".......yyy......",
  ".......yy.......",
  "......yy........",
  "......yy........",
  ".......yy.......",
  ".......yy.......",
]);

const SHARED_DORMANT: PixelMap = withSoil([
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "................",
  "......ww........",
  "......ww........",
  "......ww........",
  "......ww........",
]);

// ===== BUSH (default — round bushy shape) =====
const BUSH: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "...ll......ll...",
    "..llll....llll..",
    "..lllll..lllll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "......llll......",
    ".....llllll.....",
    "..ll..llll..ll..",
    ".llll..ss..llll.",
    ".lllll.ss.lllll.",
    "..llllsssslll...",
    "....llssssll....",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "......llll......",
    "....llllllll....",
    "...llllLlllll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  budding: withSoil([
    "....f.llll.f....",
    "....llllllll....",
    "...lfllLllfll...",
    "..lllLllllLlll..",
    "..llllllllllll..",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  flowering: withSoil([
    "...ff.llll.ff...",
    "...fFllllllFf...",
    "..llfllLlllfll..",
    "..lllLllllLlll..",
    ".lfFllllllllFfl.",
    ".lllLllssllLlll.",
    ".lllllsssslllll.",
    "..lllLssssLlll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  fruiting: withSoil([
    "......llll......",
    "....llllllll....",
    "...lllLllllll...",
    "..lfflllllffll..",
    "..lffLllllffFl..",
    ".lllLllssllLlll.",
    ".llffLssssffll..",
    "..lfFlssssfFll..",
    "...llllssllll...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  harvest: withSoil([
    "....ffllllff....",
    "...fFFllllFFf...",
    "..lffllLlllffl..",
    "..lllLllllLlll..",
    ".lffllllllllffl.",
    ".lfFLllssllLfFl.",
    ".lllllsssslllll.",
    "..lffLssssLffl..",
    "...lfFlsslfFl...",
    ".....llssll.....",
    ".......ss.......",
    ".......ss.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== ROOT (root crop — yield at soil line) =====
const ROOT: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "................",
  ]),
  budding: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "....ll....ll....",
    "...llll..llll...",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
    "......ffff......",
    "......ffFf......",
    "................",
  ]),
  harvest: withSoil([
    "....ll....ll....",
    "...llll..llll...",
    "..lllll..lllll..",
    "....lllsslll....",
    ".....llssll.....",
    "......ssss......",
    ".......ss.......",
    "......ffff......",
    ".....ffffff.....",
    ".....ffFFff.....",
    "......ffff......",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== VINE (trailing, wider than tall) =====
const VINE: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.........",
    "....llll........",
    ".....lsss.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "..ll............",
    ".llll...ll......",
    "..llssllll......",
    "....ssslll......",
    ".....sss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    ".f..........f...",
    "..ll......ll....",
    ".llll...lllll...",
    ".lLll..llLllll..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".ff........ff...",
    ".fF..ll....Ff...",
    "..ll.llll.ll....",
    ".llll..lllllff..",
    ".lLll..llLlFfl..",
    "..llssllllLll...",
    "...sssslllll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "..ff..ll..ff....",
    "..Ff.llll.Ff....",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllffLll...",
    "...sssslfFll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "..ff........ff..",
    "..FF..ll..ffFF..",
    "..ff.llll.Ffff..",
    ".llll..llllll...",
    ".lLll..llLllll..",
    "..llssllfFLll...",
    "...sssslffll....",
    "....sssslll.....",
    ".....ssss.......",
    "......ss........",
    "......ss........",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== TALL (narrow upright — corn, sunflower) =====
const TALL: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  vegetative: withSoil([
    "................",
    "......ll........",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  budding: withSoil([
    ".......f........",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  flowering: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "......lsl.......",
    ".....llsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  fruiting: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "......lsll......",
    ".....llsl.......",
    "....fflsl.......",
    "....Fflsff......",
    ".......sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  harvest: withSoil([
    "......fff.......",
    ".....fFfFf......",
    "......ffl.......",
    ".....llll.......",
    "....fflsll......",
    "....Ffls.ff.....",
    "......lsl.F.....",
    ".....flslff.....",
    "....FF.sF.......",
    ".......s........",
    ".......s........",
    ".......s........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".....yyy........",
    "......yy........",
    ".......y........",
    ".......y........",
    ".......y........",
    ".......y........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== LEAFY (low rosette — lettuce, spinach) =====
const LEAFY: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....ll..ll......",
    "...llllllll.....",
    "....llllll......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......ff........",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....fff........",
    "....fFffFf......",
    "......ll........",
    "..ll.llll.ll....",
    ".llllllLlllll...",
    ".lLlllllllLll...",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    "..ll.llll.ll....",
    ".llfllLllfllll..",
    ".lLllflllflLll..",
    "..lllllLllll....",
    "...llllllll.....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    "...ll.ll.ll.....",
    "..llllllllll....",
    ".lllllLllllll...",
    ".lLllllllllLll..",
    "..llllLlLllll...",
    "...lllllllll....",
    "....llssll......",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "...yy..yy.yy....",
    "..yyyy.yyyyy....",
    "...yyyyyyyyyy...",
    "....yyyyyyyy....",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== HERB (small, delicate) =====
const HERB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....ll.ll......",
    "......lll.......",
    "......ssl.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......f.........",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    "................",
    ".....ff.f.......",
    "....fFf.Ff......",
    "......ll........",
    ".....llll.......",
    "....ll.lll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llfl.......",
    "....llfllf......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...lll.llll.....",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== FLOWER (bloom-dominant) =====
const FLOWER: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ll.......",
    "......llll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......ll.ll.....",
    ".....lllllll....",
    "......llll......",
    "......ssll......",
    ".......ss.......",
    ".......ss.......",
    ".......ss.......",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "......ll........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    "......ff........",
    ".....f..f.......",
    "......ff........",
    ".....llll.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  flowering: withSoil([
    ".....ffff.......",
    "....fffffF......",
    "...ffFffFff.....",
    "....fffffF......",
    ".....ffff.......",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  fruiting: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  harvest: withSoil([
    "....fffff.......",
    "...fFffffF......",
    "..fffFffFfff....",
    "..ffFfffffFf....",
    "...ffffffFf.....",
    "....llllll......",
    "...ll.ssl.ll....",
    "....llssll......",
    ".....ssss.......",
    "......ss........",
    "......ss........",
    "......ss........",
  ]),
  senescence: withSoil([
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "................",
    "......yy........",
    ".....yyyy.......",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
    "......yy........",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== BULB (onion, garlic — bulb at soil line) =====
const BULB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    ".......l........",
    "......ss........",
    "......ss........",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ss........",
  ]),
  budding: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ss........",
    "......ff........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......l........",
    ".......s........",
    "......ffs.......",
    ".....ffff.......",
    "......ff........",
  ]),
  fruiting: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    "......ffs.......",
    ".....fffff......",
    ".....ffFff......",
    "......fff.......",
  ]),
  harvest: withSoil([
    ".......l........",
    "......ll........",
    ".......l........",
    "......lll.......",
    ".......l........",
    "......ll........",
    ".......s........",
    ".....ffff.......",
    "....ffffff......",
    "....fffFff......",
    ".....fffff......",
    "......fff.......",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== CLIMBING (vertical with trellis lines) =====
const CLIMBING: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wsl.......",
    "......ws........",
  ]),
  seedling: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wsl.......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  vegetative: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wsl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  budding: withSoil([
    "......ww........",
    "......wwf.......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......wslf......",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  flowering: withSoil([
    "......wwff......",
    "......wwfF......",
    "......wwl.......",
    "......wlll......",
    "......wlLl......",
    "......wslfF.....",
    "......wslff.....",
    "......wlll......",
    "......wlLl......",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  fruiting: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......wsl.......",
    "......wlfl......",
    "......wlfFl.....",
    "......wsl.......",
    "......ws........",
    "......ws........",
  ]),
  harvest: withSoil([
    "......ww........",
    "......ww........",
    "......wwl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......wsl.......",
    "......wlffl.....",
    "......wlfFl.....",
    "......wslfF.....",
    "......ws........",
    "......ws........",
  ]),
  senescence: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......wwyy......",
    "......wwy.......",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
  dormant: withSoil([
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
    "......ww........",
  ]),
};

// ===== GRASS (grass/grain — many thin blades) =====
const GRASS: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....l.l.l......",
    ".....l.l.l......",
    ".....s.s.s......",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....l.l.l.l.....",
    "....s.s.s.s.....",
    "....s.s.s.s.....",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  budding: withSoil([
    "................",
    "................",
    "...f.f.f.f.f....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  flowering: withSoil([
    "................",
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF...",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  fruiting: withSoil([
    "..ff.ff.ff.ff...",
    "..fF.fF.fF.fF...",
    "..ff.ff.ff.ff...",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...l.l.l.l.l....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  harvest: withSoil([
    "..ff.ff.ff.ff...",
    "..FF.FF.FF.FF...",
    "..ff.ff.ff.ff...",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
    "...s.s.s.s.s....",
  ]),
  senescence: withSoil([
    "................",
    "................",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
    "...y.y.y.y.y....",
  ]),
  dormant: SHARED_DORMANT,
};

// ===== COB (corn — tall stalk with tassel and ear) =====
const COB: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......l.........",
    ".....lls........",
    "......lsl.......",
    ".......s........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    ".......l........",
    "......ll........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    ".......y........",
    "......yy........",
    "......ll........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......lsll......",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  fruiting: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    "......lsfff.....",
    ".....llsffF.....",
    "......lsfff.....",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    ".......s........",
    "................",
  ]),
  harvest: withSoil([
    "......yyy.......",
    ".....yyyy.......",
    "......yl........",
    ".....llsl.......",
    ".....llsffff....",
    "......lsffFf....",
    ".....llsfffF....",
    "......lsffff....",
    ".....llsl.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== HEAD (cabbage — round ball of leaves with tight inner head) =====
const HEAD: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".......s........",
    "................",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllll......",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    ".....l...l......",
    "....ll..ll......",
    "...llllllll.....",
    "....llllll......",
    "...lllllll......",
    "....lllll.......",
    ".....lll........",
    "......s.........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "....l.....l.....",
    "...ll....ll.....",
    "..llllllllll....",
    "..lllLLLLlll....",
    "..llLLLLLLll....",
    "..lllLLLLlll....",
    "...llllllll.....",
    ".....llll.......",
    "......ss........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "...l.......l....",
    "..ll......ll....",
    "..llllllllll....",
    "..lllfffflll....",
    ".lllffFfFflll...",
    "..lllfffflll....",
    "..llllllllll....",
    "...llllllll.....",
    "....llllll......",
    "......ss........",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "..l.........l...",
    "..ll.......ll...",
    "..llllllllllll..",
    "..lllffffffll...",
    ".lllfFfffFflll..",
    "..lllffffffll...",
    "..llllllllllll..",
    "...llllllllll...",
    "....llllllll....",
    "......ss........",
    "................",
  ]),
  harvest: withSoil([
    ".l...........l..",
    ".ll.........ll..",
    "..llllllllllll..",
    "..llffffffffll..",
    ".lllfFffffFflll.",
    ".lllffFffFfflll.",
    ".lllfFffffFflll.",
    "..llffffffffll..",
    "..llllllllllll..",
    "...llllllllll...",
    "......ss........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== GOURD (melon/pumpkin — vine with big round fruit on the ground) =====
const GOURD: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "........l.......",
    ".......ls.......",
    "........s.......",
    "........s.......",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lls.......",
    ".....llls.......",
    "........s.......",
    "........s.......",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..lllll.........",
    "...lllls........",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..llfll.........",
    "...lllll........",
    "..lllllls.......",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "................",
    "....l...........",
    "...lll..........",
    "..llfll.........",
    "..llflll........",
    "...lflll........",
    "..lllllls.......",
    "....lllls.......",
    ".......ls.......",
    "........s.......",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "...l............",
    "..lll...........",
    "...llll.........",
    "....llls........",
    "......lls.......",
    ".....ffff.......",
    "....fFffFf......",
    "....ffffffs.....",
    ".....ffff.......",
    "........s.......",
    "................",
  ]),
  harvest: withSoil([
    "................",
    "..l.............",
    "..lll...........",
    "...llll.........",
    "....llls........",
    "......lls.......",
    "....fffff.......",
    "...fFffffFf.....",
    "...fFffffffs....",
    "...fFffffFf.....",
    "....fffff.......",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== CROWN (broccoli/cauliflower — stalk with dome floret head) =====
const CROWN: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lls.......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllsl......",
    "......lsl.......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    ".......l........",
    "......lll.......",
    ".....lllll......",
    "....lllllll.....",
    ".....lllsl......",
    "......lsll......",
    ".......s........",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "......fff.......",
    ".....fffff......",
    "......fff.......",
    "....llllll......",
    "...lllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    ".....fffff......",
    "....fFfffFf.....",
    ".....fffff......",
    "....llfflll.....",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  fruiting: withSoil([
    ".....fffff......",
    "....fFfffFf.....",
    "...fffFfFfff....",
    "....fFfffFf.....",
    ".....fffff......",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  harvest: withSoil([
    "....fffffff.....",
    "...fFfFffFff....",
    "..fffFfFfFfff...",
    "...fFfFffFff....",
    "....fffffff.....",
    "...llllllll.....",
    "..llllllllll....",
    "....llllsl......",
    ".....lsll.......",
    "......ls........",
    ".......s........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== BERRY (strawberry/blueberry — low bush with dangling fruit) =====
const BERRY: Record<StageKey, PixelMap> = {
  planted: SHARED_PLANTED,
  germination: SHARED_GERMINATION,
  sprout: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......l........",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  seedling: withSoil([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "......lll.......",
    ".....lllll......",
    "......lsl.......",
    ".......s........",
    "................",
    "................",
  ]),
  vegetative: withSoil([
    "................",
    "................",
    "................",
    "................",
    ".....llll.......",
    "....lllLll......",
    "...llLllLll.....",
    "....lllLll......",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    "................",
  ]),
  budding: withSoil([
    "................",
    "................",
    "................",
    ".....llll.......",
    "....lllLll......",
    "...llLllLll.....",
    "....lllLlll.....",
    "....lflLfll.....",
    ".....llll.......",
    "......lsl.......",
    ".......s........",
    "................",
  ]),
  flowering: withSoil([
    "................",
    "................",
    "....lllll.......",
    "...lllLlll......",
    "..lllLllLlll....",
    "...llLllLll.....",
    "...lflLlfll.....",
    "....lfffl.......",
    ".....llll.......",
    "......lsl.......",
    "......ss........",
    "................",
  ]),
  fruiting: withSoil([
    "................",
    "................",
    "....lllll.......",
    "...lllLlll......",
    "..lllLllLlll....",
    "...llLllLll.....",
    "....lllLlll.....",
    "...ff.ff.ff.....",
    "....f.fF.f......",
    ".....ff.ff......",
    "......ss........",
    "................",
  ]),
  harvest: withSoil([
    "................",
    "...llllll.......",
    "..lllLlllll.....",
    "..llLlllLlll....",
    "...llLllLll.....",
    "....lllLlll.....",
    "..fff.fff.ff....",
    "..fFf.fFf.fF....",
    "...ff..ff..f....",
    "....ff.fff......",
    "......ss........",
    "................",
  ]),
  senescence: SHARED_SENESCENCE,
  dormant: SHARED_DORMANT,
};

// ===== Hand-crafted 32×32 stages =====

// --- BUSH 32×32 (full detail for all growth stages) ---
const BUSH_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  ".......lllll......lllll",
  "........lllll....lllll",
  ".........llllllllllll",
  "..........llllsslll",
  "............llssll",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........llllll",
  "..........llllllll",
  ".........lllllllll",
  "....ll....lllll....ll",
  "...llll...llll....llll",
  "...lllll...ss...lllll",
  "....lllll..ss..lllll",
  ".....llllssssslll",
  ".......llsssslll",
  ".........ssss",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "...........lllllll",
  ".........lllllllllll",
  "........llllllLlllllll",
  ".......lllLlllllllLlll",
  "......lllllllllllllllll",
  ".....llllLllllllllLlllll",
  ".....lllllllllllllllllll",
  "......llllLllllllLllll",
  ".....llllllllllllllllll",
  "......lllLlllsslllLlll",
  ".......llllllssssllll",
  "........lllLssssLlll",
  "..........lllssslll",
  "............lsssl",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_BUDDING: PixelMap = withSoil32(r32([
  "........f..lllllll..f",
  ".........lllllllllll",
  "........lfllllLlllfll",
  ".......lllLlllllllLlll",
  "......llllllfllllllflll",
  ".....lllLllllllllllLlllf",
  ".....lllllllllllllllllll",
  "......lllLllllllllLllll",
  ".....llllllllllllllllll",
  "......lllLlllsslllLlll",
  ".......llllllssssllll",
  "........lllLssssLlll",
  "..........lllssslll",
  "............lsssl",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_FLOWERING: PixelMap = withSoil32(r32([
  "......ff..lllllll..ff",
  "......fFl.llllllll.lFf",
  ".......llfllLlllllfll",
  "......lllLlllllllLlll",
  ".....lfFllllllllllllFfl",
  ".....lllLlllllllllLllll",
  "....fFlllllllllllllllFf",
  ".....lllLllllllllLlllll",
  "......llllllllllllllll",
  "......lllLlllsslllLlll",
  ".......llllllssssllll",
  "........lllLssssLlll",
  "..........lllssslll",
  "............lsssl",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "..........lllllllll",
  ".........lllllLlllllll",
  "........llfllllllllfll",
  ".......lfflLllllllffLl",
  "......lllllllllllllllll",
  ".....lllLlllllllllLlllll",
  ".....lllffllllllllffllll",
  "......llfFllllllllfFlll",
  ".....lllllllllllllllllll",
  "......lllLlllsslllLlll",
  ".......llfflssssffll",
  "........llfFsssslfFl",
  "..........lllssslll",
  "............lsssl",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BUSH_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  ".......ffl.lllllll.lff",
  "......fFFlllllllllllFFf",
  ".......llfflLlllllffl",
  "......lllLlllllllLllll",
  ".....lffllllllllllllffl",
  ".....lfFLllllllllllLfFl",
  "....lllllllllllllllllllll",
  ".....lfflLllllllllLffll",
  "......llfFlllllllllfFl",
  "......lllLlllsslllLlll",
  ".......llllllssssllll",
  "........lfFLssssLfFl",
  "..........lfFlsslfFl",
  "............lsssl",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

// --- ROOT 32×32 (full detail — foliage above, root swells below soil) ---
const ROOT_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............ll",
  ".............llll",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "........llllssllll",
  "..........llssll",
  ".............ssss",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "......lllll........lllll",
  ".......lllllssllllll",
  "..........llssll",
  "...........ssss",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "..............ss",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "......lllll........lllll",
  ".......lllllssllllll",
  "..........llssll",
  "...........ssss",
  "..............ss",
  "..............ss",
  "..............ss",
  ".............ffff",
  "..............ff",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "......lllll........lllll",
  ".......lllllssllllll",
  "..........llssll",
  "...........ssss",
  "..............ss",
  "..............ss",
  "..............ss",
  "............ffffff",
  "............fffFff",
  ".............ffff",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "......lllll........lllll",
  ".......lllllssllllll",
  "..........llssll",
  "...........ssss",
  "..............ss",
  "..............ss",
  ".............ffff",
  "............ffffff",
  "............fffFff",
  ".............ffFf",
  "..............ff",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const ROOT_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "........ll..........ll",
  ".......llll........llll",
  "......llllll......llllll",
  ".......lllllssllllll",
  "..........llssll",
  "...........ssss",
  "..............ss",
  "............ffffff",
  "...........ffffffff",
  "...........ffFfffFf",
  "...........fffFffff",
  "............ffFfff",
  ".............fffff",
  "..............fff",
  "...............f",
  "",
  "",
  "",
  "",
  "",
]));

// --- VINE 32×32 hand-crafted (3/10) ---

const VINE_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..........ll",
  "..........lll",
  ".........llll",
  "..........lsss",
  "...........ss",
  "...........ss",
]));

const VINE_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "....ll",
  "...llll......ll",
  "....llss...llll",
  "......ssssllLl",
  ".......ssslll",
  "........sss",
  ".........ss",
  ".........ss",
  ".........ss",
  "",
  "",
]));

const VINE_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "....ll..........ll",
  "...llll.......lllll",
  "...lLll......llLlll",
  "....llss...lllLll",
  "......sssslllll",
  ".......sssslll",
  "........sssslll",
  ".......sssss..lll",
  "......ssss...llLll",
  ".....sss.....lllll",
  "......ss......lll",
  "......ss",
  "......ss",
  "......ss",
  "",
  "",
]));

const VINE_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "..f...........f",
  "",
  "....ll..........ll",
  "...llll.......lllll",
  "...lLll......llLlll",
  "....llss...lllLll",
  "......sssslllll",
  ".......sssslll..f",
  "........sssslll",
  ".......sssss..lll",
  "......ssss...llLll",
  ".....sss.....lllll",
  "......ss......lll",
  "......ss",
  "......ss",
  "......ss",
  "......ss",
  "",
]));

const VINE_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  ".ff...........ff",
  ".fF..ll........Ff",
  "....llll.......lllll",
  "...lLlll.....llLlll",
  "...lLll......llLlll",
  "....llss...lllLll",
  "..ff..sssslllll",
  "..Ff...sssslll..ff",
  "........sssslll.Ff",
  ".......sssss..lll",
  "......ssss...llLll",
  ".....sss..ff.lllll",
  "......ss..Ff..lll",
  "......ss",
  "......ss",
  "......ss",
  "......ss",
  "",
  "",
]));

const VINE_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "..ff..ll........ff",
  "..Ff.llll.......Ff",
  "...lllll......lllll",
  "...lLlll.....llLlll",
  "...lLll......llLlll",
  "....llss...lllLll",
  "......sssslllll",
  ".......sssslll",
  "........sssslll",
  ".......sssss..lll",
  "......ssss...llLll",
  ".....sss..ff.lllll",
  ".fFF.ss...fFf.lll",
  "..fFf.ss..fFf",
  "...ff..ss..ff",
  "......ss",
  "......ss",
  "......ss",
  "",
  "",
]));

const VINE_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "..ff..ll.........ff",
  "..FF.llll........Ff",
  "..ff.llll.......lllll",
  "...lllll......llLlll",
  "...lLlll.....llLlll",
  "...lLll.....fflLll",
  "....llss...fFflll",
  "......sssslffll",
  ".......sssslll",
  "........sssslll",
  ".......sssss..lll",
  "......ssss...llLll",
  ".fFf.sss..fFf.llll",
  ".fFFfss...fFFf.lll",
  "..fFFf.ss.fFFf",
  "...ff..ss..ff",
  "......ss",
  "......ss",
  "......ss",
  "",
  "",
]));

// --- TALL 32×32 hand-crafted (4/10) ---

const TALL_32_SPROUT: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "..............l",
  ".............ll",
  "..............sl",
  "..............s",
  "..............s",
  "..............s",
]));

const TALL_32_SEEDLING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "............lsl",
  ".............sl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
]));

const TALL_32_VEGETATIVE: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "............ll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_BUDDING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "",
  "",
  ".............ff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_FLOWERING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsll",
  "..........llsl",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "............lsll",
  "..........llsl",
  "........fflsll",
  "........Fflsl",
  "...........lsff",
  "..........llslFf",
  "...........lsl",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

const TALL_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "...........fffff",
  "..........fFfFfFf",
  "...........ffFff",
  "............ffll",
  "...........llll",
  "........fflslll",
  "........FFlsl",
  "........fflsll",
  "........Fflsl",
  "...........lsff",
  "..........llslFF",
  "...........lslff",
  ".............sFF",
  "..............sf",
  "..............s",
  "..............s",
  "..............s",
  "..............s",
  "",
  "",
]));

// --- COB, HEAD, GOURD, CROWN, BERRY overrides (fruiting + harvest) ---

const COB_32_FRUITING: PixelMap = withSoil32(r32([
  "............yyyyy",
  "...........yyyyyy",
  "............yyyy",
  "...........llyl",
  "..........lllsl",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  "..........llslfffff",
  ".........lllslffFfff",
  "..........llslfffffFf",
  ".........lllslffFfff",
  "..........llslfffff",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  "..........lls",
  "............ls",
  ".............s",
  ".............s",
  ".............s",
  ".............s",
  "",
  "",
]));

const COB_32_HARVEST: PixelMap = withSoil32(r32([
  "............yyyyy",
  "...........yyyyyy",
  "............yyyy",
  "...........llyyl",
  "..........lllsl",
  ".........lllsl",
  "..........llslll",
  ".........lllsl",
  ".........lllslffffffl",
  "..........llslffFfFffl",
  ".........lllslfffffFfFf",
  "..........llslffFffFffl",
  ".........lllslfffffFfFf",
  "..........llslffFfFffl",
  ".........lllslffffffl",
  "..........llsl",
  ".........lllsl",
  "..........lls",
  "............ls",
  ".............s",
  ".............s",
  ".............s",
  ".............s",
  "",
]));

const HEAD_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "....l...............l",
  "...ll..............ll",
  "...lllll......lllll",
  "...llllllllllllllll",
  "..lllllllllllllllll",
  "..lllllffffffffllll",
  "..llllffFffffffflll",
  ".lllllffFfffFfffllll",
  ".lllllfffffffffflll",
  "..llllffFfffFffflll",
  "..lllllffffffffllll",
  "..lllllllllllllllll",
  "...llllllllllllllll",
  "....llllllllllllll",
  ".....lllllllllll",
  "......llllllllll",
  "........llll",
  ".........ss",
  ".........ss",
  "",
  "",
  "",
]));

const HEAD_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "..l.................l",
  "..ll...............ll",
  "..lllll.......lllll",
  "..lllllllllllllllllll",
  "..llllllllllllllllllll",
  ".llllllfffffffffflllll",
  ".lllllffFfffFfFffflll",
  ".llllffFfFfffffFFfflll",
  ".llllfffffffFfffffllll",
  ".llllffFfffFfFfFffflll",
  ".llllfffFfffffFfFfflll",
  ".lllllffFfffFfFffflll",
  ".llllllfffffffffflllll",
  "..llllllllllllllllllll",
  "..lllllllllllllllllll",
  "...lllllllllllllllll",
  "....llllllllllllll",
  ".....lllllllllll",
  ".........ssss",
  ".........ss",
  "",
  "",
  "",
]));

const GOURD_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "......l",
  ".....lll",
  "....lllll",
  ".....lllll",
  "......lllls",
  ".......lllls",
  ".........llls",
  "...........lls",
  "..........fffff",
  ".........fFfffFf",
  "........fFffffffFf",
  "........ffffffffff",
  "........fFffffffFf",
  ".........fFfffFf",
  "..........fffff",
  "..............s",
  "..............s",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const GOURD_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "....l",
  "....lll",
  ".....llll",
  "......lllls",
  ".......lllls",
  "..........llls",
  "............lls",
  ".........fffffff",
  "........fFfffffFf",
  ".......fFfffffffffFf",
  "......fFfffFfffFfffFf",
  "......ffffffFffffffFf",
  "......fFfffFfffFfffFfs",
  ".......fFfffffffffFf",
  "........fFfffffFf",
  ".........fffffff",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const CROWN_32_FRUITING: PixelMap = withSoil32(r32([
  ".........fffffffffff",
  "........fFfffFfffFff",
  ".......fffFfFfFfFffff",
  "......fffffFfFfFfffff",
  ".......fffFfFfFfFffff",
  "........fFfffFfffFff",
  ".........fffffffffff",
  ".......llllllllllll",
  "......lllllllllllllll",
  ".....llllllllllllllll",
  "......lllllllllllllll",
  ".......llllllllllsl",
  "........lllllllslll",
  ".........llllslll",
  "..........llsll",
  "...........lsl",
  "............ls",
  ".............s",
  ".............s",
  "",
  "",
  "",
  "",
  "",
]));

const CROWN_32_HARVEST: PixelMap = withSoil32(r32([
  "........fffffffffffff",
  ".......fFfFffFfFffFff",
  "......ffffFfFfFfFffffff",
  ".....fFfFffFffFffFfFfff",
  ".....fffffFfFfFfFfFffff",
  "......fFfFffFffFffFfFf",
  ".......ffffFfFfFfffff",
  "........fffffffffffff",
  ".......llllllllllllll",
  "......llllllllllllllll",
  ".....lllllllllllllllll",
  "......llllllllllllllll",
  ".......llllllllllsl",
  "........llllllslll",
  ".........lllslll",
  "..........llsll",
  "...........lsl",
  "............ls",
  ".............s",
  "",
  "",
  "",
  "",
  "",
]));

const BERRY_32_FRUITING: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  "",
  "........llllllll",
  ".......llllLllll",
  "......lllLllllLlll",
  ".....llllLllllLllll",
  "......lllLllllLllll",
  ".......llllLlllll",
  "........llllllllll",
  "......ff..fff..ff",
  ".......ff..fF..ff",
  "........f...f...f",
  "..........ff..ff",
  "...........ff",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

const BERRY_32_HARVEST: PixelMap = withSoil32(r32([
  "",
  "",
  "",
  ".......lllllllll",
  "......llllLllllll",
  ".....lllLllllLllll",
  "....llllLllllLlllll",
  ".....lllLllllLlllll",
  "......llllLlllllll",
  ".....fff.ffff.fff",
  "....fFff.fFfF.fFff",
  "....fff..ffff..fff",
  ".....ff.fffff.fff",
  "......ff.fFfF.ff",
  ".......ff.fff.f",
  "........ff..ff",
  "............ss",
  "............ss",
  "",
  "",
  "",
  "",
  "",
  "",
]));

/** All shape families keyed by SpriteShape, at 32×32 resolution. */
export const SHAPE_MAPS: Record<SpriteShape, Record<StageKey, PixelMap>> = {
  bush: {
    ...upscaleShape(BUSH),
    sprout: BUSH_32_SPROUT,
    seedling: BUSH_32_SEEDLING,
    vegetative: BUSH_32_VEGETATIVE,
    budding: BUSH_32_BUDDING,
    flowering: BUSH_32_FLOWERING,
    fruiting: BUSH_32_FRUITING,
    harvest: BUSH_32_HARVEST,
  },
  root: {
    ...upscaleShape(ROOT),
    sprout: ROOT_32_SPROUT,
    seedling: ROOT_32_SEEDLING,
    vegetative: ROOT_32_VEGETATIVE,
    budding: ROOT_32_BUDDING,
    flowering: ROOT_32_FLOWERING,
    fruiting: ROOT_32_FRUITING,
    harvest: ROOT_32_HARVEST,
  },
  vine: {
    ...upscaleShape(VINE),
    sprout: VINE_32_SPROUT,
    seedling: VINE_32_SEEDLING,
    vegetative: VINE_32_VEGETATIVE,
    budding: VINE_32_BUDDING,
    flowering: VINE_32_FLOWERING,
    fruiting: VINE_32_FRUITING,
    harvest: VINE_32_HARVEST,
  },
  tall: {
    ...upscaleShape(TALL),
    sprout: TALL_32_SPROUT,
    seedling: TALL_32_SEEDLING,
    vegetative: TALL_32_VEGETATIVE,
    budding: TALL_32_BUDDING,
    flowering: TALL_32_FLOWERING,
    fruiting: TALL_32_FRUITING,
    harvest: TALL_32_HARVEST,
  },
  leafy: upscaleShape(LEAFY),
  herb: upscaleShape(HERB),
  flower: upscaleShape(FLOWER),
  bulb: upscaleShape(BULB),
  climbing: upscaleShape(CLIMBING),
  grass: upscaleShape(GRASS),
  cob: { ...upscaleShape(COB), fruiting: COB_32_FRUITING, harvest: COB_32_HARVEST },
  head: { ...upscaleShape(HEAD), fruiting: HEAD_32_FRUITING, harvest: HEAD_32_HARVEST },
  gourd: { ...upscaleShape(GOURD), fruiting: GOURD_32_FRUITING, harvest: GOURD_32_HARVEST },
  crown: { ...upscaleShape(CROWN), fruiting: CROWN_32_FRUITING, harvest: CROWN_32_HARVEST },
  berry: { ...upscaleShape(BERRY), fruiting: BERRY_32_FRUITING, harvest: BERRY_32_HARVEST },
};

// Keep legacy exports for backwards compatibility
export const STAGE_MAPS = BUSH;
export const ROOT_STAGE_MAPS: Partial<Record<StageKey, PixelMap>> = {
  fruiting: ROOT.fruiting,
  harvest: ROOT.harvest,
};

/** Maps must stay 16×16 and only use palette slots; verified by tests. */
export const PALETTE_SLOTS = new Set([
  ".",
  "m",
  "M",
  "s",
  "l",
  "L",
  "f",
  "F",
  "y",
  "w",
]);
